import { Exhibition, Venue } from './types';

// Bundled tonal placeholders — stand-ins until venue press images are set
// via the admin edit screen or the exhibitions.image_url column.
export const PLACEHOLDERS: Record<string, number> = {
  archibald: require('../../assets/exhibitions/archibald.png'),
  murakami: require('../../assets/exhibitions/murakami.png'),
  primavera: require('../../assets/exhibitions/primavera.png'),
  armanious: require('../../assets/exhibitions/armanious.png'),
  kahukiwa: require('../../assets/exhibitions/kahukiwa.png'),
  nell: require('../../assets/exhibitions/nell.png'),
  'constructed-world': require('../../assets/exhibitions/constructed-world.png'),
  bennett: require('../../assets/exhibitions/bennett.png'),
  'gabori-ledgerwood': require('../../assets/exhibitions/gabori-ledgerwood.png'),
  'infinite-gesture': require('../../assets/exhibitions/infinite-gesture.png'),
  crothers: require('../../assets/exhibitions/crothers.png'),
  pulse: require('../../assets/exhibitions/pulse.png'),
  abbotsleigh: require('../../assets/exhibitions/abbotsleigh.png'),
};

export const FALLBACK_PLACEHOLDER = PLACEHOLDERS.archibald;

export const SEED_VENUES: Venue[] = [
  { id: 'v-agnsw', name: 'Art Gallery of New South Wales', slug: 'art-gallery-of-new-south-wales', type: 'museum', address: 'Art Gallery Road, The Domain, Sydney NSW 2000', suburb: 'The Domain', website: 'https://www.artgallery.nsw.gov.au', instagram: '@artgalleryofnsw', latitude: -33.8688, longitude: 151.2173, city: 'Sydney', owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://upload.wikimedia.org/wikipedia/commons/4/42/Art_Gallery_of_New_South_Wales.JPG'},
  { id: 'v-mca', name: 'MCA Australia', slug: 'mca-australia', type: 'museum', address: '140 George Street, The Rocks, Sydney NSW 2000', suburb: 'The Rocks', website: 'https://www.mca.com.au', instagram: '@mca_australia', latitude: -33.8599, longitude: 151.2088, city: 'Sydney', owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/The_Museum_of_Contemporary_Art%2C_Sydney_%28former_MSB_Building%29.jpg'},
  { id: 'v-roslynoxley9', name: 'Roslyn Oxley9 Gallery', slug: 'roslyn-oxley9-gallery', type: 'gallery', address: '8 Soudan Lane, Paddington NSW 2021', suburb: 'Paddington', website: 'https://www.roslynoxley9.com.au', instagram: null, latitude: null, longitude: null, city: 'Sydney', owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null},
  { id: 'v-cassandrabird', name: 'Cassandra Bird', slug: 'cassandra-bird', type: 'gallery', address: '54 Kellett Street, Potts Point NSW 2011', suburb: 'Potts Point', website: null, instagram: null, latitude: null, longitude: null, city: 'Sydney', owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null},
  { id: 'v-1301sw', name: '1301SW', slug: '1301sw', type: 'gallery', address: '3 Hiles Street, Alexandria NSW 2015', suburb: 'Alexandria', website: null, instagram: null, latitude: null, longitude: null, city: 'Sydney', owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null},
  { id: 'v-amesyavuz', name: 'Ames Yavuz', slug: 'ames-yavuz', type: 'gallery', address: '114 Commonwealth Street, Surry Hills NSW 2010', suburb: 'Surry Hills', website: null, instagram: null, latitude: null, longitude: null, city: 'Sydney', owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null},
  { id: 'v-olsen', name: 'OLSEN Annexe', slug: 'olsen-annexe', type: 'gallery', address: '74 Queen Street, Woollahra NSW 2025', suburb: 'Woollahra', website: null, instagram: null, latitude: null, longitude: null, city: 'Sydney', owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null},
  { id: 'v-gcs', name: 'Grace Cossington Smith Gallery', slug: 'grace-cossington-smith-gallery', type: 'gallery', address: 'Gate 7, 1666 Pacific Highway, Wahroonga NSW 2076', suburb: 'Wahroonga', website: null, instagram: null, latitude: null, longitude: null, city: 'Sydney', owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null},
  { id: "v-articulate-project-space", name: "Articulate Project Space", slug: "articulate-project-space", type: "ari", address: "497 Parramatta Road, Leichhardt NSW", suburb: "Leichhardt", website: "https://www.articulateprojectspace.org", instagram: "@articulateprojectspace", latitude: -33.8776, longitude: 151.1552, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-boomalli", name: "Boomalli Aboriginal Artists Co-operative", slug: "boomalli", type: "ari", address: "55–59 Flood Street, Leichhardt NSW", suburb: "Leichhardt", website: "https://boomalli.com.au", instagram: "@boomalli_aboriginal_art", latitude: -33.8858, longitude: 151.1504, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-firstdraft", name: "Firstdraft", slug: "firstdraft", type: "ari", address: "13–17 Riley Street, Woolloomooloo NSW", suburb: "Woolloomooloo", website: "https://firstdraft.org.au", instagram: "@firstdraft_", latitude: -33.8725, longitude: 151.2155, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-frontyard-projects", name: "Frontyard Projects", slug: "frontyard-projects", type: "ari", address: "228 Illawarra Road, Marrickville NSW", suburb: "Marrickville", website: "https://www.frontyardprojects.org", instagram: "@frontyardorg", latitude: -33.9107, longitude: 151.1549, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-pari", name: "Pari", slug: "pari", type: "ari", address: "Shop 7, 14 Hunter Street, Parramatta NSW", suburb: "Parramatta", website: "https://pariari.org", instagram: "@pari_ari_", latitude: -33.813, longitude: 150.9987, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-scratch-art-space", name: "Scratch Art Space", slug: "scratch-art-space", type: "ari", address: "67 Sydenham Road, Marrickville NSW", suburb: "Marrickville", website: "https://www.scratchartspace.com", instagram: "@scratchartspace", latitude: -33.9065, longitude: 151.1614, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-tortuga-studios", name: "Tortuga Studios", slug: "tortuga-studios", type: "ari", address: "31 Princes Highway, St Peters NSW", suburb: "St Peters", website: "https://tortugastudios.org.au", instagram: "@tortuga.studios", latitude: -33.91, longitude: 151.1808, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-4a-centre", name: "4A Centre for Contemporary Asian Art", slug: "4a-centre", type: "gallery", address: "181–187 Hay Street, Haymarket NSW", suburb: "Haymarket", website: "https://4a.com.au", instagram: "@4a_aus", latitude: -33.879, longitude: 151.2037, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-arthouse-gallery", name: "Arthouse Gallery", slug: "arthouse-gallery", type: "gallery", address: "66 McLachlan Avenue, Rushcutters Bay NSW", suburb: "Rushcutters Bay", website: "https://arthousegallery.com.au", instagram: "@arthousegallery", latitude: -33.8781, longitude: 151.2236, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-artspace", name: "Artspace", slug: "artspace", type: "gallery", address: "43–51 Cowper Wharf Roadway (The Gunnery), Woolloomooloo NSW", suburb: "Woolloomooloo", website: "https://www.artspace.org.au", instagram: "@artspacesydney", latitude: -33.8696, longitude: 151.2205, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-australian-galleries-sydney", name: "Australian Galleries", slug: "australian-galleries-sydney", type: "gallery", address: "15 Roylston Street, Paddington NSW", suburb: "Paddington", website: "https://australiangalleries.com.au", instagram: "@australiangalleries", latitude: -33.881, longitude: 151.2246, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-bankstown-arts-centre", name: "Bankstown Arts Centre", slug: "bankstown-arts-centre", type: "gallery", address: "5 Olympic Parade, Bankstown NSW", suburb: "Bankstown", website: "https://www.bankstownartscentre.com.au", instagram: "@bankstownartscentre", latitude: -33.9185, longitude: 151.0342, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-coma-gallery", name: "COMA Gallery", slug: "coma-gallery", type: "gallery", address: "37 Chapel Street, Marrickville NSW", suburb: "Marrickville", website: "https://www.comagallery.com", instagram: "@comagallery", latitude: -33.9078, longitude: 151.164, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-campbelltown-arts-centre", name: "Campbelltown Arts Centre", slug: "campbelltown-arts-centre", type: "gallery", address: "1 Art Gallery Road, Campbelltown NSW", suburb: "Campbelltown", website: "https://c-a-c.com.au", instagram: "@campbelltownartscentre", latitude: -34.0728, longitude: 150.809, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-carriageworks", name: "Carriageworks", slug: "carriageworks", type: "gallery", address: "245 Wilson Street, Eveleigh NSW", suburb: "Eveleigh", website: "https://carriageworks.com.au", instagram: "@carriageworks", latitude: -33.8946, longitude: 151.1935, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-chalk-horse", name: "Chalk Horse", slug: "chalk-horse", type: "gallery", address: "167 William Street (lower ground), Darlinghurst NSW", suburb: "Darlinghurst", website: "https://www.chalkhorse.com.au", instagram: "@chalkhorsegallery", latitude: -33.875, longitude: 151.2189, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-china-heights", name: "China Heights Gallery", slug: "china-heights", type: "gallery", address: "Level 3, 16–28 Foster Street, Surry Hills NSW", suburb: "Surry Hills", website: "https://chinaheights.com", instagram: "@chinaheights", latitude: -33.8797, longitude: 151.2103, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-darren-knight-gallery", name: "Darren Knight Gallery", slug: "darren-knight-gallery", type: "gallery", address: "840 Elizabeth Street, Waterloo NSW", suburb: "Waterloo", website: "https://darrenknightgallery.com", instagram: "@darrenknightgallery", latitude: -33.907, longitude: 151.2072, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-dominik-mersch-gallery", name: "Dominik Mersch Gallery", slug: "dominik-mersch-gallery", type: "gallery", address: "1/75 McLachlan Avenue, Rushcutters Bay NSW", suburb: "Rushcutters Bay", website: "https://dominikmerschgallery.com", instagram: "@dominikmerschgallery", latitude: -33.8783, longitude: 151.2238, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-fine-arts-sydney", name: "Fine Arts, Sydney", slug: "fine-arts-sydney", type: "gallery", address: "23 Hampden Street, Paddington NSW", suburb: "Paddington", website: "https://www.finearts.sydney", instagram: "@fineartssydney", latitude: -33.8828, longitude: 151.2211, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-gallery-lane-cove", name: "Gallery Lane Cove", slug: "gallery-lane-cove", type: "gallery", address: "Level 3, 164 Longueville Road, Lane Cove NSW", suburb: "Lane Cove", website: "https://www.gallerylanecove.com.au", instagram: "@gallerylanecove", latitude: -33.816, longitude: 151.1697, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-granville-centre-art-gallery", name: "Granville Centre Art Gallery", slug: "granville-centre-art-gallery", type: "gallery", address: "1 Memorial Drive, Granville NSW", suburb: "Granville", website: "https://www.cumberland.nsw.gov.au/granville-centre-art-gallery", instagram: "@granvillecentreartgallery", latitude: -33.831, longitude: 151.014, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-hazelhurst-arts-centre", name: "Hazelhurst Arts Centre", slug: "hazelhurst-arts-centre", type: "gallery", address: "782 Kingsway, Gymea NSW", suburb: "Gymea", website: "https://hazelhurst.sutherlandshire.nsw.gov.au", instagram: "@hazelhurstartscentre", latitude: -34.0329, longitude: 151.0874, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-king-street-gallery", name: "King Street Gallery on William", slug: "king-street-gallery", type: "gallery", address: "177 William Street, Darlinghurst NSW", suburb: "Darlinghurst", website: "https://kingstreetgallery.com.au", instagram: "@kingstreetgallery", latitude: -33.8747, longitude: 151.2184, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-liverpool-powerhouse", name: "Liverpool Powerhouse", slug: "liverpool-powerhouse", type: "gallery", address: "1 Powerhouse Road, Casula NSW", suburb: "Casula", website: "https://www.liverpoolpowerhouse.com.au", instagram: "@liverpoolpowerhouse", latitude: -33.9493, longitude: 150.9129, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-liverpool-street-gallery", name: "Liverpool Street Gallery", slug: "liverpool-street-gallery", type: "gallery", address: "243a Liverpool Street, Darlinghurst NSW", suburb: "Darlinghurst", website: "https://www.liverpoolstgallery.com.au", instagram: "@liverpoolstreetgallery", latitude: -33.8777, longitude: 151.2152, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-manly-art-gallery-museum", name: "Manly Art Gallery & Museum", slug: "manly-art-gallery-museum", type: "gallery", address: "1a West Esplanade, Manly NSW", suburb: "Manly", website: "https://www.northernbeaches.nsw.gov.au/things-to-do/arts-and-culture/manly-art-gallery-museum", instagram: "@magamnsw", latitude: -33.7986, longitude: 151.2814, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-martin-browne-contemporary", name: "Martin Browne Contemporary", slug: "martin-browne-contemporary", type: "gallery", address: "15 Hampden Street, Paddington NSW", suburb: "Paddington", website: "https://martinbrownecontemporary.com", instagram: "@martinbrownecontemporary", latitude: -33.8825, longitude: 151.2338, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-michael-reid-sydney", name: "Michael Reid Sydney", slug: "michael-reid-sydney", type: "gallery", address: "109 Shepherd Street, Chippendale NSW", suburb: "Chippendale", website: "https://michaelreid.com.au", instagram: "@michaelreidsydney", latitude: -33.8877, longitude: 151.1951, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-mosman-art-gallery", name: "Mosman Art Gallery", slug: "mosman-art-gallery", type: "gallery", address: "1 Art Gallery Way, Mosman NSW", suburb: "Mosman", website: "https://mosmanartgallery.org.au", instagram: "@mosmanart", latitude: -33.8279, longitude: 151.2406, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-n-smith-gallery", name: "N.Smith Gallery", slug: "n-smith-gallery", type: "gallery", address: "15 Foster Street, Surry Hills NSW", suburb: "Surry Hills", website: "https://www.nsmithgallery.com", instagram: "@n.smithgallery", latitude: -33.88, longitude: 151.2097, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-nanda-hobbs", name: "Nanda\\Hobbs", slug: "nanda-hobbs", type: "gallery", address: "12–14 Meagher Street, Chippendale NSW", suburb: "Chippendale", website: "https://nandahobbs.com", instagram: "@nandahobbs", latitude: -33.8867, longitude: 151.1986, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-nas-gallery", name: "National Art School Gallery", slug: "nas-gallery", type: "gallery", address: "156 Forbes Street, Darlinghurst NSW", suburb: "Darlinghurst", website: "https://nas.edu.au", instagram: "@nas_au", latitude: -33.8788, longitude: 151.2172, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-olsen-gallery", name: "Olsen Gallery", slug: "olsen-gallery", type: "gallery", address: "63 Jersey Road, Woollahra NSW", suburb: "Woollahra", website: "https://www.olsengallery.com", instagram: "@olsen_gallery", latitude: -33.8875, longitude: 151.2337, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-penrith-regional-gallery", name: "Penrith Regional Gallery", slug: "penrith-regional-gallery", type: "gallery", address: "86 River Road, Emu Plains NSW", suburb: "Emu Plains", website: "https://www.penrithregionalgallery.com.au", instagram: "@penrithregionalgallery", latitude: -33.7458, longitude: 150.6669, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-phoenix-central-park", name: "Phoenix Central Park", slug: "phoenix-central-park", type: "gallery", address: "37–49 O'Connor Street, Chippendale NSW", suburb: "Chippendale", website: "https://phoenixcentralpark.com.au", instagram: "@phoenixcentralpark", latitude: -33.8865, longitude: 151.199, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-sh-ervin-gallery", name: "S.H. Ervin Gallery", slug: "sh-ervin-gallery", type: "gallery", address: "Watson Road, Observatory Hill, Millers Point NSW", suburb: "Millers Point", website: "https://www.shervingallery.com.au", instagram: "@shervingallery", latitude: -33.8599, longitude: 151.2049, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-station-sydney", name: "STATION Sydney", slug: "station-sydney", type: "gallery", address: "91 Campbell Street, Surry Hills NSW", suburb: "Surry Hills", website: "https://stationgallery.com", instagram: "@stationgalleryaustralia", latitude: -33.8796, longitude: 151.2102, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-saint-cloche", name: "Saint Cloche", slug: "saint-cloche", type: "gallery", address: "37 MacDonald Street, Paddington NSW", suburb: "Paddington", website: "https://saintcloche.com", instagram: "@saint_cloche", latitude: -33.8824, longitude: 151.2231, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-sullivan-strumpf", name: "Sullivan+Strumpf", slug: "sullivan-strumpf", type: "gallery", address: "799 Elizabeth Street, Zetland NSW", suburb: "Zetland", website: "https://www.sullivanstrumpf.com", instagram: "@sullivanstrumpf", latitude: -33.9065, longitude: 151.2067, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-unsw-galleries", name: "UNSW Galleries", slug: "unsw-galleries", type: "gallery", address: "Cnr Oxford Street & Greens Road, Paddington NSW", suburb: "Paddington", website: "https://www.galleries.unsw.edu.au", instagram: "@unswgalleries", latitude: -33.8845, longitude: 151.2223, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-uts-gallery", name: "UTS Gallery", slug: "uts-gallery", type: "gallery", address: "Level 4, Building 6, 702 Harris Street, Ultimo NSW", suburb: "Ultimo", website: "https://art.uts.edu.au", instagram: "@uts_art", latitude: -33.8805, longitude: 151.2, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-utopia-art-sydney", name: "Utopia Art Sydney", slug: "utopia-art-sydney", type: "gallery", address: "983 Bourke Street, Waterloo NSW", suburb: "Waterloo", website: "https://utopiaartsydney.com.au", instagram: "@utopiaartsydney", latitude: -33.9, longitude: 151.2106, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-verge-gallery", name: "Verge Gallery", slug: "verge-gallery", type: "gallery", address: "Jane Foss Russell Plaza, 154 City Road, Darlington NSW", suburb: "Darlington", website: "https://www.verge-gallery.net", instagram: "@vergegallery", latitude: -33.8888, longitude: 151.1866, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-australian-museum", name: "Australian Museum", slug: "australian-museum", type: "museum", address: "1 William Street, Sydney NSW", suburb: "Sydney", website: "https://australian.museum", instagram: "@australianmuseum", latitude: -33.8712, longitude: 151.2133, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-chau-chak-wing-museum", name: "Chau Chak Wing Museum", slug: "chau-chak-wing-museum", type: "museum", address: "University Place, University of Sydney, Camperdown NSW", suburb: "Camperdown", website: "https://www.sydney.edu.au/museum/", instagram: "@ccwm_sydney", latitude: -33.8853, longitude: 151.1905, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-fairfield-city-museum-gallery", name: "Fairfield City Museum & Gallery", slug: "fairfield-city-museum-gallery", type: "museum", address: "634 The Horsley Drive, Smithfield NSW", suburb: "Smithfield", website: "https://www.fcmg.nsw.gov.au", instagram: "@fairfieldcitymuseumgallery", latitude: -33.8481, longitude: 150.9427, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-museum-of-sydney", name: "Museum of Sydney", slug: "museum-of-sydney", type: "museum", address: "Cnr Phillip & Bridge Streets, Sydney NSW", suburb: "Sydney", website: "https://mhnsw.au/visit-us/museum-of-sydney/", instagram: "@museumsofhistorynsw", latitude: -33.8636, longitude: 151.2114, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-powerhouse-parramatta", name: "Powerhouse Parramatta", slug: "powerhouse-parramatta", type: "museum", address: "34 Phillip Street, Parramatta NSW", suburb: "Parramatta", website: "https://powerhouse.com.au/visit/parramatta", instagram: "@powerhousemuseum", latitude: -33.81, longitude: 151.0044, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-sydney-jewish-museum", name: "Sydney Jewish Museum", slug: "sydney-jewish-museum", type: "museum", address: "148 Darlinghurst Road, Darlinghurst NSW", suburb: "Darlinghurst", website: "https://sydneyjewishmuseum.com.au", instagram: "@sydneyjewishmuseum", latitude: -33.879, longitude: 151.2203, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-white-rabbit-gallery", name: "White Rabbit Gallery", slug: "white-rabbit-gallery", type: "museum", address: "30 Balfour Street, Chippendale NSW", suburb: "Chippendale", website: "https://whiterabbitcollection.org", instagram: "@whiterabbitgallery", latitude: -33.8865, longitude: 151.2003, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
];

export const SEED_EXHIBITIONS: Exhibition[] = [
  {
    id: 'e-archibald',
    venue_id: 'v-agnsw',
    title: 'Archibald, Wynne & Sulman Prizes 2026',
    artists: 'Finalists 2026',
    start_date: '2026-06-06',
    end_date: '2026-08-16',
    opening_datetime: null,
    description:
      'Australia’s most argued-over walls. The Archibald’s portraits, the Wynne’s landscapes and the Sulman’s subject pictures hang side by side — a yearly census of who we are and how we want to be seen.',
    image_url: 'asset:archibald',
    status: 'approved',
    rejection_reason: null,
    is_featured: true,
    city: 'Sydney',
  },
  {
    id: 'e-murakami',
    venue_id: 'v-agnsw',
    title: 'Takashi Murakami',
    artists: 'Takashi Murakami',
    start_date: '2026-05-30',
    end_date: '2026-09-27',
    opening_datetime: null,
    description:
      'The superflat universe at full scale — smiling flowers, silver screens and centuries of Japanese painting compressed into one relentless surface. Murakami’s first major Sydney survey.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/8/80/Takashi_Murakami_at_Versailles_Sept._2010_%281%29.jpg',
    status: 'approved',
    rejection_reason: null,
    is_featured: true,
    city: 'Sydney',
  },
  {
    id: 'e-primavera',
    venue_id: 'v-mca',
    title: 'Primavera 2026: Young Australian Artists',
    artists: 'Young Australian Artists',
    start_date: '2026-07-03',
    end_date: '2026-09-20',
    opening_datetime: null,
    description:
      'The MCA’s annual exhibition of Australian artists aged 35 and under — the clearest early signal of where Australian art is going next.',
    image_url: 'asset:primavera',
    status: 'approved',
    rejection_reason: null,
    is_featured: true,
    city: 'Sydney',
  },
  {
    id: 'e-armanious',
    venue_id: 'v-mca',
    title: 'Hany Armanious',
    artists: 'Hany Armanious',
    start_date: '2026-06-20',
    end_date: '2026-08-31',
    opening_datetime: null,
    description:
      'Casts of the overlooked — foam, wax, candle stubs, offcuts — remade with such fidelity that the ordinary turns uncanny. A survey of one of Australia’s most quietly influential sculptors.',
    image_url: 'asset:armanious',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-kahukiwa',
    venue_id: 'v-mca',
    title: 'Robyn Kahukiwa',
    artists: 'Robyn Kahukiwa',
    start_date: '2026-06-20',
    end_date: '2026-08-31',
    opening_datetime: null,
    description:
      'Paintings that carry whakapapa like a current — the late Māori artist’s figures of women and ancestors, political and tender at once, gathered for Sydney audiences.',
    image_url: 'asset:kahukiwa',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-nell',
    venue_id: 'v-mca',
    title: 'Nell: Sculpture Commission',
    artists: 'Nell',
    start_date: '2026-05-01',
    end_date: '2026-10-18',
    opening_datetime: null,
    description:
      'A new commission by Nell — where rock’n’roll, Buddhism and the eucalypt meet. On the MCA’s public-facing spaces through spring.',
    image_url: 'asset:nell',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-constructed-world',
    venue_id: 'v-roslynoxley9',
    title: 'A Constructed World',
    artists: 'A Constructed World',
    start_date: '2026-06-26',
    end_date: '2026-07-18',
    opening_datetime: null,
    description:
      'The collaborative practice of Geoff Lowe and Jacqueline Riva — painting, performance and speech acts that keep meaning deliberately unstable.',
    image_url: 'asset:constructed-world',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-bennett',
    venue_id: 'v-cassandrabird',
    title: 'Places of Delight',
    artists: 'Robby Bennett',
    start_date: '2026-07-03',
    end_date: '2026-07-25',
    opening_datetime: null,
    description:
      'New paintings by Robby Bennett — gardens, rooms and remembered places rendered as sites of pleasure and slight unease.',
    image_url: 'asset:bennett',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-gabori-ledgerwood',
    venue_id: 'v-1301sw',
    title: 'Sally Gabori & Judy Ledgerwood',
    artists: 'Sally Gabori, Judy Ledgerwood',
    start_date: '2026-06-13',
    end_date: '2026-07-11',
    opening_datetime: null,
    description:
      'Two painters of colour at scale, an ocean apart — Gabori’s Kaiadilt country in saturated fields beside Ledgerwood’s rhythmic Chicago abstraction.',
    image_url: 'asset:gabori-ledgerwood',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-infinite-gesture',
    venue_id: 'v-amesyavuz',
    title: 'Infinite Gesture',
    artists: 'Group Exhibition',
    start_date: '2026-06-27',
    end_date: '2026-08-08',
    opening_datetime: null,
    description:
      'A group exhibition on the mark as a unit of thought — gesture repeated, extended and abstracted across painting and works on paper.',
    image_url: 'asset:infinite-gesture',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-crothers',
    venue_id: 'v-olsen',
    title: 'Interconnected',
    artists: 'Aaron Crothers',
    start_date: '2026-07-22',
    end_date: '2026-08-15',
    opening_datetime: '2026-07-22T18:00:00+10:00',
    description:
      'Aaron Crothers maps the systems beneath landscape — geology, weather, root and network — in paintings that read like aerial diagrams of connection.',
    image_url: 'asset:crothers',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-pulse',
    venue_id: 'v-gcs',
    title: 'Pulse',
    artists: 'Group Exhibition',
    start_date: '2026-06-12',
    end_date: '2026-07-11',
    opening_datetime: null,
    description:
      'Works that take rhythm as subject and method — repetition, beat and breath across media at the Grace Cossington Smith Gallery.',
    image_url: 'asset:pulse',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-abbotsleigh',
    venue_id: 'v-gcs',
    title: 'Abbotsleigh Biennial: Finalists',
    artists: 'Biennial Finalists',
    start_date: '2026-07-18',
    end_date: '2026-08-15',
    opening_datetime: '2026-07-18T14:00:00+10:00',
    description:
      'Finalists of the Abbotsleigh Biennial — a cross-section of current practice selected for the gallery’s biennial exhibition and prize.',
    image_url: 'asset:abbotsleigh',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
];
