import { Exhibition, Venue } from './types';

// Bundled tonal placeholders — stand-ins until venue press images are set
// via the admin edit screen or the exhibitions.image_url column.
export const PLACEHOLDERS: Record<string, number> = {
  archibald: require('../../assets/exhibitions/archibald.png'),
  murakami: require('../../assets/exhibitions/murakami.png'),
  primavera: require('../../assets/exhibitions/primavera.png'),
  armanious: require('../../assets/exhibitions/armanious.png'),
  kahukiwa: require('../../assets/exhibitions/kahukiwa.png'),
  nell: require('../../assets/exhibitions/nell.png'),
  'constructed-world': require('../../assets/exhibitions/constructed-world.png'),
  bennett: require('../../assets/exhibitions/bennett.png'),
  'gabori-ledgerwood': require('../../assets/exhibitions/gabori-ledgerwood.png'),
  'infinite-gesture': require('../../assets/exhibitions/infinite-gesture.png'),
  crothers: require('../../assets/exhibitions/crothers.png'),
  pulse: require('../../assets/exhibitions/pulse.png'),
  abbotsleigh: require('../../assets/exhibitions/abbotsleigh.png'),
};

export const FALLBACK_PLACEHOLDER = PLACEHOLDERS.archibald;

export const SEED_VENUES: Venue[] = [
  { id: 'v-agnsw', name: 'Art Gallery of New South Wales', type: 'museum', address: 'Art Gallery Road, The Domain, Sydney NSW 2000', city: 'Sydney', owner_user_id: null , image_url: 'https://upload.wikimedia.org/wikipedia/commons/4/42/Art_Gallery_of_New_South_Wales.JPG'},
  { id: 'v-mca', name: 'MCA Australia', type: 'museum', address: '140 George Street, The Rocks, Sydney NSW 2000', city: 'Sydney', owner_user_id: null , image_url: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/The_Museum_of_Contemporary_Art%2C_Sydney_%28former_MSB_Building%29.jpg'},
  { id: 'v-roslynoxley9', name: 'Roslyn Oxley9 Gallery', type: 'gallery', address: '8 Soudan Lane, Paddington NSW 2021', city: 'Sydney', owner_user_id: null , image_url: null},
  { id: 'v-cassandrabird', name: 'Cassandra Bird', type: 'gallery', address: '54 Kellett Street, Potts Point NSW 2011', city: 'Sydney', owner_user_id: null , image_url: null},
  { id: 'v-1301sw', name: '1301SW', type: 'gallery', address: '3 Hiles Street, Alexandria NSW 2015', city: 'Sydney', owner_user_id: null , image_url: null},
  { id: 'v-amesyavuz', name: 'Ames Yavuz', type: 'gallery', address: '114 Commonwealth Street, Surry Hills NSW 2010', city: 'Sydney', owner_user_id: null , image_url: null},
  { id: 'v-olsen', name: 'OLSEN Annexe', type: 'gallery', address: '74 Queen Street, Woollahra NSW 2025', city: 'Sydney', owner_user_id: null , image_url: null},
  { id: 'v-gcs', name: 'Grace Cossington Smith Gallery', type: 'gallery', address: 'Gate 7, 1666 Pacific Highway, Wahroonga NSW 2076', city: 'Sydney', owner_user_id: null , image_url: null},
];

export const SEED_EXHIBITIONS: Exhibition[] = [
  {
    id: 'e-archibald',
    venue_id: 'v-agnsw',
    title: 'Archibald, Wynne & Sulman Prizes 2026',
    artists: 'Finalists 2026',
    start_date: '2026-06-06',
    end_date: '2026-08-16',
    opening_datetime: null,
    description:
      'Australia’s most argued-over walls. The Archibald’s portraits, the Wynne’s landscapes and the Sulman’s subject pictures hang side by side — a yearly census of who we are and how we want to be seen.',
    image_url: 'asset:archibald',
    status: 'approved',
    rejection_reason: null,
    is_featured: true,
    city: 'Sydney',
  },
  {
    id: 'e-murakami',
    venue_id: 'v-agnsw',
    title: 'Takashi Murakami',
    artists: 'Takashi Murakami',
    start_date: '2026-05-30',
    end_date: '2026-09-27',
    opening_datetime: null,
    description:
      'The superflat universe at full scale — smiling flowers, silver screens and centuries of Japanese painting compressed into one relentless surface. Murakami’s first major Sydney survey.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/8/80/Takashi_Murakami_at_Versailles_Sept._2010_%281%29.jpg',
    status: 'approved',
    rejection_reason: null,
    is_featured: true,
    city: 'Sydney',
  },
  {
    id: 'e-primavera',
    venue_id: 'v-mca',
    title: 'Primavera 2026: Young Australian Artists',
    artists: 'Young Australian Artists',
    start_date: '2026-07-03',
    end_date: '2026-09-20',
    opening_datetime: null,
    description:
      'The MCA’s annual exhibition of Australian artists aged 35 and under — the clearest early signal of where Australian art is going next.',
    image_url: 'asset:primavera',
    status: 'approved',
    rejection_reason: null,
    is_featured: true,
    city: 'Sydney',
  },
  {
    id: 'e-armanious',
    venue_id: 'v-mca',
    title: 'Hany Armanious',
    artists: 'Hany Armanious',
    start_date: '2026-06-20',
    end_date: '2026-08-31',
    opening_datetime: null,
    description:
      'Casts of the overlooked — foam, wax, candle stubs, offcuts — remade with such fidelity that the ordinary turns uncanny. A survey of one of Australia’s most quietly influential sculptors.',
    image_url: 'asset:armanious',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-kahukiwa',
    venue_id: 'v-mca',
    title: 'Robyn Kahukiwa',
    artists: 'Robyn Kahukiwa',
    start_date: '2026-06-20',
    end_date: '2026-08-31',
    opening_datetime: null,
    description:
      'Paintings that carry whakapapa like a current — the late Māori artist’s figures of women and ancestors, political and tender at once, gathered for Sydney audiences.',
    image_url: 'asset:kahukiwa',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-nell',
    venue_id: 'v-mca',
    title: 'Nell: Sculpture Commission',
    artists: 'Nell',
    start_date: '2026-05-01',
    end_date: '2026-10-18',
    opening_datetime: null,
    description:
      'A new commission by Nell — where rock’n’roll, Buddhism and the eucalypt meet. On the MCA’s public-facing spaces through spring.',
    image_url: 'asset:nell',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-constructed-world',
    venue_id: 'v-roslynoxley9',
    title: 'A Constructed World',
    artists: 'A Constructed World',
    start_date: '2026-06-26',
    end_date: '2026-07-18',
    opening_datetime: null,
    description:
      'The collaborative practice of Geoff Lowe and Jacqueline Riva — painting, performance and speech acts that keep meaning deliberately unstable.',
    image_url: 'asset:constructed-world',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-bennett',
    venue_id: 'v-cassandrabird',
    title: 'Places of Delight',
    artists: 'Robby Bennett',
    start_date: '2026-07-03',
    end_date: '2026-07-25',
    opening_datetime: null,
    description:
      'New paintings by Robby Bennett — gardens, rooms and remembered places rendered as sites of pleasure and slight unease.',
    image_url: 'asset:bennett',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-gabori-ledgerwood',
    venue_id: 'v-1301sw',
    title: 'Sally Gabori & Judy Ledgerwood',
    artists: 'Sally Gabori, Judy Ledgerwood',
    start_date: '2026-06-13',
    end_date: '2026-07-11',
    opening_datetime: null,
    description:
      'Two painters of colour at scale, an ocean apart — Gabori’s Kaiadilt country in saturated fields beside Ledgerwood’s rhythmic Chicago abstraction.',
    image_url: 'asset:gabori-ledgerwood',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-infinite-gesture',
    venue_id: 'v-amesyavuz',
    title: 'Infinite Gesture',
    artists: 'Group Exhibition',
    start_date: '2026-06-27',
    end_date: '2026-08-08',
    opening_datetime: null,
    description:
      'A group exhibition on the mark as a unit of thought — gesture repeated, extended and abstracted across painting and works on paper.',
    image_url: 'asset:infinite-gesture',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-crothers',
    venue_id: 'v-olsen',
    title: 'Interconnected',
    artists: 'Aaron Crothers',
    start_date: '2026-07-22',
    end_date: '2026-08-15',
    opening_datetime: '2026-07-22T18:00:00+10:00',
    description:
      'Aaron Crothers maps the systems beneath landscape — geology, weather, root and network — in paintings that read like aerial diagrams of connection.',
    image_url: 'asset:crothers',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-pulse',
    venue_id: 'v-gcs',
    title: 'Pulse',
    artists: 'Group Exhibition',
    start_date: '2026-06-12',
    end_date: '2026-07-11',
    opening_datetime: null,
    description:
      'Works that take rhythm as subject and method — repetition, beat and breath across media at the Grace Cossington Smith Gallery.',
    image_url: 'asset:pulse',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-abbotsleigh',
    venue_id: 'v-gcs',
    title: 'Abbotsleigh Biennial: Finalists',
    artists: 'Biennial Finalists',
    start_date: '2026-07-18',
    end_date: '2026-08-15',
    opening_datetime: '2026-07-18T14:00:00+10:00',
    description:
      'Finalists of the Abbotsleigh Biennial — a cross-section of current practice selected for the gallery’s biennial exhibition and prize.',
    image_url: 'asset:abbotsleigh',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
];
