import { Exhibition, Venue } from './types';

// Bundled tonal placeholders — stand-ins until venue press images are set
// via the admin edit screen or the exhibitions.image_url column.
export const PLACEHOLDERS: Record<string, number> = {
  archibald: require('../../assets/exhibitions/archibald.png'),
  murakami: require('../../assets/exhibitions/murakami.png'),
  primavera: require('../../assets/exhibitions/primavera.png'),
  armanious: require('../../assets/exhibitions/armanious.png'),
  kahukiwa: require('../../assets/exhibitions/kahukiwa.png'),
  nell: require('../../assets/exhibitions/nell.png'),
  'constructed-world': require('../../assets/exhibitions/constructed-world.png'),
  bennett: require('../../assets/exhibitions/bennett.png'),
  'gabori-ledgerwood': require('../../assets/exhibitions/gabori-ledgerwood.png'),
  'infinite-gesture': require('../../assets/exhibitions/infinite-gesture.png'),
  crothers: require('../../assets/exhibitions/crothers.png'),
  pulse: require('../../assets/exhibitions/pulse.png'),
  abbotsleigh: require('../../assets/exhibitions/abbotsleigh.png'),
};

export const FALLBACK_PLACEHOLDER = PLACEHOLDERS.archibald;

export const SEED_VENUES: Venue[] = [
  { id: 'v-agnsw', founded_year: 1871, free_entry: true, entry_checked: "2026-07-22", opening_hours: 'Daily 10:00–17:00, Wed until 22:00', hours_checked: '2026-07-21', name: 'Art Gallery of New South Wales', slug: 'art-gallery-of-new-south-wales', type: 'museum', address: 'Art Gallery Road, The Domain, Sydney NSW 2000', suburb: 'The Domain', website: 'https://www.artgallery.nsw.gov.au', instagram: '@artgalleryofnsw', latitude: -33.8688, longitude: 151.2173, city: 'Sydney', owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://upload.wikimedia.org/wikipedia/commons/4/42/Art_Gallery_of_New_South_Wales.JPG'},
  { id: 'v-mca', founded_year: 1991, free_entry: false, entry_checked: "2026-07-22", opening_hours: 'Wed–Mon 10:00–17:00, closed Tue', hours_checked: '2026-07-21', name: 'MCA Australia', slug: 'mca-australia', type: 'museum', address: '140 George Street, The Rocks, Sydney NSW 2000', suburb: 'The Rocks', website: 'https://www.mca.com.au', instagram: '@mca_australia', latitude: -33.8599, longitude: 151.2088, city: 'Sydney', owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://upload.wikimedia.org/wikipedia/commons/f/f5/The_Museum_of_Contemporary_Art%2C_Sydney_%28former_MSB_Building%29.jpg'},
  { id: 'v-roslynoxley9', opening_hours: 'Tue–Fri 10:00–18:00, Sat 11:00–18:00', hours_checked: '2026-07-21', name: 'Roslyn Oxley9 Gallery', slug: 'roslyn-oxley9-gallery', type: 'gallery', address: '8 Soudan Lane, Paddington NSW 2021', suburb: 'Paddington', website: 'https://www.roslynoxley9.com.au', instagram: '@roslynoxley9', latitude: null, longitude: null, city: 'Sydney', owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Roslyn_Oxley9_Gallery.jpg?width=1600'},
  { id: 'v-cassandrabird', opening_hours: 'Tue–Fri 10:00–17:00, Sat 11:00–17:00', hours_checked: '2026-07-21', name: 'Cassandra Bird', slug: 'cassandra-bird', type: 'gallery', address: '54 Kellett Street, Potts Point NSW 2011', suburb: 'Potts Point', website: 'https://www.cassandrabird.com/', instagram: '@cassandrabird.gallery', latitude: null, longitude: null, city: 'Sydney', owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null},
  { id: 'v-1301sw', name: '1301SW', slug: '1301sw', type: 'gallery', address: '3 Hiles Street, Alexandria NSW 2015', suburb: 'Alexandria', website: 'https://www.1301sw.com/', instagram: '@1301sw_au', latitude: null, longitude: null, city: 'Sydney', owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null},
  { id: 'v-amesyavuz', opening_hours: 'Tue–Sat 10:00–18:00', hours_checked: '2026-07-21', name: 'Ames Yavuz', slug: 'ames-yavuz', type: 'gallery', address: '114 Commonwealth Street, Surry Hills NSW 2010', suburb: 'Surry Hills', website: 'https://amesyavuz.com/', instagram: '@amesyavuz', latitude: null, longitude: null, city: 'Sydney', owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null},
  { id: 'v-olsen', opening_hours: 'Tue–Fri 10:00–18:00, Sat 10:00–17:00', hours_checked: '2026-07-21', name: 'OLSEN Annexe', slug: 'olsen-annexe', type: 'gallery', address: '74 Queen Street, Woollahra NSW 2025', suburb: 'Woollahra', website: 'https://www.olsengallery.com/', instagram: '@olsen_annexe', latitude: null, longitude: null, city: 'Sydney', owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null},
  { id: 'v-gcs', opening_hours: 'Tue–Sat 10:00–17:00 (during exhibitions)', hours_checked: '2026-07-21', name: 'Grace Cossington Smith Gallery', slug: 'grace-cossington-smith-gallery', type: 'gallery', address: 'Gate 7, 1666 Pacific Highway, Wahroonga NSW 2076', suburb: 'Wahroonga', website: null, instagram: '@gcsgallery', latitude: null, longitude: null, city: 'Sydney', owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null},
  { id: "v-articulate-project-space", name: "Articulate Project Space", slug: "articulate-project-space", type: "ari", address: "497 Parramatta Road, Leichhardt NSW", suburb: "Leichhardt", website: "https://www.articulateprojectspace.org", instagram: "@articulateprojectspace", latitude: -33.8776, longitude: 151.1552, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-boomalli", name: "Boomalli Aboriginal Artists Co-operative", slug: "boomalli", type: "ari", address: "55–59 Flood Street, Leichhardt NSW", suburb: "Leichhardt", website: "https://boomalli.com.au", instagram: "@boomalli_aboriginal_art", latitude: -33.8858, longitude: 151.1504, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-firstdraft", opening_hours: 'Wed 11:00–20:00, Thu–Sat 11:00–17:00', hours_checked: '2026-07-21', name: "Firstdraft", slug: "firstdraft", type: "ari", address: "13–17 Riley Street, Woolloomooloo NSW", suburb: "Woolloomooloo", website: "https://firstdraft.org.au", instagram: "@firstdraft_", latitude: -33.8725, longitude: 151.2155, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-frontyard-projects", name: "Frontyard Projects", slug: "frontyard-projects", type: "ari", address: "228 Illawarra Road, Marrickville NSW", suburb: "Marrickville", website: "https://www.frontyardprojects.org", instagram: "@frontyardorg", latitude: -33.9107, longitude: 151.1549, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-pari", name: "Pari", slug: "pari", type: "ari", address: "Shop 7, 14 Hunter Street, Parramatta NSW", suburb: "Parramatta", website: "https://pariari.org", instagram: "@pari_ari_", latitude: -33.813, longitude: 150.9987, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-scratch-art-space", name: "Scratch Art Space", slug: "scratch-art-space", type: "ari", address: "67 Sydenham Road, Marrickville NSW", suburb: "Marrickville", website: "https://www.scratchartspace.com", instagram: "@scratchartspace", latitude: -33.9065, longitude: 151.1614, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-tortuga-studios", name: "Tortuga Studios", slug: "tortuga-studios", type: "ari", address: "31 Princes Highway, St Peters NSW", suburb: "St Peters", website: "https://tortugastudios.org.au", instagram: "@tortuga.studios", latitude: -33.91, longitude: 151.1808, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-4a-centre", founded_year: 1996, free_entry: true, entry_checked: "2026-07-22", name: "4A Centre for Contemporary Asian Art", slug: "4a-centre", type: "gallery", address: "181–187 Hay Street, Haymarket NSW", suburb: "Haymarket", website: "https://4a.com.au", instagram: "@4a_aus", latitude: -33.879, longitude: 151.2037, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-arthouse-gallery", name: "Arthouse Gallery", slug: "arthouse-gallery", type: "gallery", address: "66 McLachlan Avenue, Rushcutters Bay NSW", suburb: "Rushcutters Bay", website: "https://arthousegallery.com.au", instagram: "@arthousegallery", latitude: -33.8781, longitude: 151.2236, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-artspace", founded_year: 1983, free_entry: true, entry_checked: "2026-07-22", opening_hours: 'Tue–Sun 11:00–17:00', hours_checked: '2026-07-21', name: "Artspace", slug: "artspace", type: "gallery", address: "43–51 Cowper Wharf Roadway (The Gunnery), Woolloomooloo NSW", suburb: "Woolloomooloo", website: "https://www.artspace.org.au", instagram: "@artspacesydney", latitude: -33.8696, longitude: 151.2205, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Artspace%2C_The_Gunnery%2C_Woolloomooloo.jpg?width=1600' },
  { id: "v-australian-galleries-sydney", name: "Australian Galleries", slug: "australian-galleries-sydney", type: "gallery", address: "15 Roylston Street, Paddington NSW", suburb: "Paddington", website: "https://australiangalleries.com.au", instagram: "@australiangalleries", latitude: -33.881, longitude: 151.2246, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-bankstown-arts-centre", name: "Bankstown Arts Centre", slug: "bankstown-arts-centre", type: "gallery", address: "5 Olympic Parade, Bankstown NSW", suburb: "Bankstown", website: "https://www.bankstownartscentre.com.au", instagram: "@bankstownartscentre", latitude: -33.9185, longitude: 151.0342, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-coma-gallery", name: "COMA Gallery", slug: "coma-gallery", type: "gallery", address: "37 Chapel Street, Marrickville NSW", suburb: "Marrickville", website: "https://www.comagallery.com", instagram: "@comagallery", latitude: -33.9078, longitude: 151.164, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-campbelltown-arts-centre", opening_hours: 'Daily 10:00–16:00', hours_checked: '2026-07-21', name: "Campbelltown Arts Centre", slug: "campbelltown-arts-centre", type: "gallery", address: "1 Art Gallery Road, Campbelltown NSW", suburb: "Campbelltown", website: "https://c-a-c.com.au", instagram: "@campbelltownartscentre", latitude: -34.0728, longitude: 150.809, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-carriageworks", founded_year: 2007, free_entry: true, entry_checked: "2026-07-22", name: "Carriageworks", slug: "carriageworks", type: "gallery", address: "245 Wilson Street, Eveleigh NSW", suburb: "Eveleigh", website: "https://carriageworks.com.au", instagram: "@carriageworks", latitude: -33.8946, longitude: 151.1935, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-chalk-horse", name: "Chalk Horse", slug: "chalk-horse", type: "gallery", address: "167 William Street (lower ground), Darlinghurst NSW", suburb: "Darlinghurst", website: "https://www.chalkhorse.com.au", instagram: "@chalkhorsegallery", latitude: -33.875, longitude: 151.2189, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-china-heights", name: "China Heights Gallery", slug: "china-heights", type: "gallery", address: "Level 3, 16–28 Foster Street, Surry Hills NSW", suburb: "Surry Hills", website: "https://chinaheights.com", instagram: "@chinaheights", latitude: -33.8797, longitude: 151.2103, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-darren-knight-gallery", name: "Darren Knight Gallery", slug: "darren-knight-gallery", type: "gallery", address: "840 Elizabeth Street, Waterloo NSW", suburb: "Waterloo", website: "https://darrenknightgallery.com", instagram: "@darrenknightgallery", latitude: -33.907, longitude: 151.2072, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-dominik-mersch-gallery", name: "Dominik Mersch Gallery", slug: "dominik-mersch-gallery", type: "gallery", address: "1/75 McLachlan Avenue, Rushcutters Bay NSW", suburb: "Rushcutters Bay", website: "https://dominikmerschgallery.com", instagram: "@dominikmerschgallery", latitude: -33.8783, longitude: 151.2238, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-fine-arts-sydney", name: "Fine Arts, Sydney", slug: "fine-arts-sydney", type: "gallery", address: "23 Hampden Street, Paddington NSW", suburb: "Paddington", website: "https://www.finearts.sydney", instagram: "@fineartssydney", latitude: -33.8828, longitude: 151.2211, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-gallery-lane-cove", name: "Gallery Lane Cove", slug: "gallery-lane-cove", type: "gallery", address: "Level 3, 164 Longueville Road, Lane Cove NSW", suburb: "Lane Cove", website: "https://www.gallerylanecove.com.au", instagram: "@gallerylanecove", latitude: -33.816, longitude: 151.1697, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-granville-centre-art-gallery", name: "Granville Centre Art Gallery", slug: "granville-centre-art-gallery", type: "gallery", address: "1 Memorial Drive, Granville NSW", suburb: "Granville", website: "https://www.cumberland.nsw.gov.au/granville-centre-art-gallery", instagram: "@granvillecentreartgallery", latitude: -33.831, longitude: 151.014, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-hazelhurst-arts-centre", name: "Hazelhurst Arts Centre", slug: "hazelhurst-arts-centre", type: "gallery", address: "782 Kingsway, Gymea NSW", suburb: "Gymea", website: "https://hazelhurst.sutherlandshire.nsw.gov.au", instagram: "@hazelhurstartscentre", latitude: -34.0329, longitude: 151.0874, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-king-street-gallery", opening_hours: 'Tue–Sat 10:00–18:00', hours_checked: '2026-07-21', name: "King Street Gallery on William", slug: "king-street-gallery", type: "gallery", address: "177 William Street, Darlinghurst NSW", suburb: "Darlinghurst", website: "https://kingstreetgallery.com.au", instagram: "@kingstreetgallery", latitude: -33.8747, longitude: 151.2184, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-liverpool-powerhouse", name: "Casula Powerhouse Arts Centre", slug: "liverpool-powerhouse", type: "gallery", address: "1 Powerhouse Road, Casula NSW", suburb: "Casula", website: "https://www.liverpoolpowerhouse.com.au", instagram: "@liverpoolpowerhouse", latitude: -33.9493, longitude: 150.9129, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-manly-art-gallery-museum", opening_hours: 'Tue–Sun 10:00–17:00', hours_checked: '2026-07-21', name: "Manly Art Gallery & Museum", slug: "manly-art-gallery-museum", type: "gallery", address: "1a West Esplanade, Manly NSW", suburb: "Manly", website: "https://www.northernbeaches.nsw.gov.au/things-to-do/arts-and-culture/manly-art-gallery-museum", instagram: "@magamnsw", latitude: -33.7986, longitude: 151.2814, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Manly_Art_Gallery_and_Museum_pano.jpg?width=1600' },
  { id: "v-martin-browne-contemporary", name: "Martin Browne Contemporary", slug: "martin-browne-contemporary", type: "gallery", address: "15 Hampden Street, Paddington NSW", suburb: "Paddington", website: "https://martinbrownecontemporary.com", instagram: "@martinbrownecontemporary", latitude: -33.8825, longitude: 151.2338, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-michael-reid-sydney", name: "Michael Reid Sydney", slug: "michael-reid-sydney", type: "gallery", address: "109 Shepherd Street, Chippendale NSW", suburb: "Chippendale", website: "https://michaelreid.com.au", instagram: "@michaelreidsydney", latitude: -33.8877, longitude: 151.1951, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-mosman-art-gallery", opening_hours: 'Daily 10:00–17:00', hours_checked: '2026-07-21', name: "Mosman Art Gallery", slug: "mosman-art-gallery", type: "gallery", address: "1 Art Gallery Way, Mosman NSW", suburb: "Mosman", website: "https://mosmanartgallery.org.au", instagram: "@mosmanart", latitude: -33.8279, longitude: 151.2406, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-n-smith-gallery", name: "N.Smith Gallery", slug: "n-smith-gallery", type: "gallery", address: "15 Foster Street, Surry Hills NSW", suburb: "Surry Hills", website: "https://www.nsmithgallery.com", instagram: "@n.smithgallery", latitude: -33.88, longitude: 151.2097, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-nanda-hobbs", name: "Nanda\\Hobbs", slug: "nanda-hobbs", type: "gallery", address: "12–14 Meagher Street, Chippendale NSW", suburb: "Chippendale", website: "https://nandahobbs.com", instagram: "@nandahobbs", latitude: -33.8867, longitude: 151.1986, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-nas-gallery", name: "National Art School Gallery", slug: "nas-gallery", type: "gallery", address: "156 Forbes Street, Darlinghurst NSW", suburb: "Darlinghurst", website: "https://nas.edu.au", instagram: "@nas_au", latitude: -33.8788, longitude: 151.2172, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/(1)_National_Art_School_(d).JPG?width=1600' },
  { id: "v-olsen-gallery", name: "Olsen Gallery", slug: "olsen-gallery", type: "gallery", address: "63 Jersey Road, Woollahra NSW", suburb: "Woollahra", website: "https://www.olsengallery.com", instagram: "@olsen_gallery", latitude: -33.8875, longitude: 151.2337, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-penrith-regional-gallery", name: "Penrith Regional Gallery", slug: "penrith-regional-gallery", type: "gallery", address: "86 River Road, Emu Plains NSW", suburb: "Emu Plains", website: "https://www.penrithregionalgallery.com.au", instagram: "@penrithregionalgallery", latitude: -33.7458, longitude: 150.6669, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-phoenix-central-park", name: "Phoenix Central Park", slug: "phoenix-central-park", type: "gallery", address: "37–49 O'Connor Street, Chippendale NSW", suburb: "Chippendale", website: "https://phoenixcentralpark.com.au", instagram: "@phoenixcentralpark", latitude: -33.8865, longitude: 151.199, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-sh-ervin-gallery", opening_hours: 'Tue–Sun 11:00–17:00', hours_checked: '2026-07-21', name: "S.H. Ervin Gallery", slug: "sh-ervin-gallery", type: "gallery", address: "Watson Road, Observatory Hill, Millers Point NSW", suburb: "Millers Point", website: "https://www.shervingallery.com.au", instagram: "@shervingallery", latitude: -33.8599, longitude: 151.2049, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/S._H._Ervin_Gallery_1.jpg?width=1600' },
  { id: "v-station-sydney", name: "STATION Sydney", slug: "station-sydney", type: "gallery", address: "91 Campbell Street, Surry Hills NSW", suburb: "Surry Hills", website: "https://stationgallery.com", instagram: "@stationgalleryaustralia", latitude: -33.8796, longitude: 151.2102, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-saint-cloche", name: "Saint Cloche", slug: "saint-cloche", type: "gallery", address: "37 MacDonald Street, Paddington NSW", suburb: "Paddington", website: "https://saintcloche.com", instagram: "@saint_cloche", latitude: -33.8824, longitude: 151.2231, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-sullivan-strumpf", name: "Sullivan+Strumpf", slug: "sullivan-strumpf", type: "gallery", address: "799 Elizabeth Street, Zetland NSW", suburb: "Zetland", website: "https://www.sullivanstrumpf.com", instagram: "@sullivanstrumpf", latitude: -33.9065, longitude: 151.2067, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-unsw-galleries", name: "UNSW Galleries", slug: "unsw-galleries", type: "gallery", address: "Cnr Oxford Street & Greens Road, Paddington NSW", suburb: "Paddington", website: "https://www.galleries.unsw.edu.au", instagram: "@unswgalleries", latitude: -33.8845, longitude: 151.2223, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-uts-gallery", name: "UTS Gallery", slug: "uts-gallery", type: "gallery", address: "Level 4, Building 6, 702 Harris Street, Ultimo NSW", suburb: "Ultimo", website: "https://art.uts.edu.au", instagram: "@uts_art", latitude: -33.8805, longitude: 151.2, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-utopia-art-sydney", name: "Utopia Art Sydney", slug: "utopia-art-sydney", type: "gallery", address: "983 Bourke Street, Waterloo NSW", suburb: "Waterloo", website: "https://utopiaartsydney.com.au", instagram: "@utopiaartsydney", latitude: -33.9, longitude: 151.2106, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-verge-gallery", name: "Verge Gallery", slug: "verge-gallery", type: "gallery", address: "Jane Foss Russell Plaza, 154 City Road, Darlington NSW", suburb: "Darlington", website: "https://www.verge-gallery.net", instagram: "@vergegallery", latitude: -33.8888, longitude: 151.1866, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-australian-museum", founded_year: 1827, free_entry: true, entry_checked: "2026-07-22", name: "Australian Museum", slug: "australian-museum", type: "museum", address: "1 William Street, Sydney NSW", suburb: "Sydney", website: "https://australian.museum", instagram: "@australianmuseum", latitude: -33.8712, longitude: 151.2133, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/AustralianMuseum.jpg?width=1600' },
  { id: "v-chau-chak-wing-museum", founded_year: 2020, free_entry: true, entry_checked: "2026-07-22", opening_hours: 'Mon–Fri 10:00–17:00, Sat–Sun 12:00–16:00', hours_checked: '2026-07-21', name: "Chau Chak Wing Museum", slug: "chau-chak-wing-museum", type: "museum", address: "University Place, University of Sydney, Camperdown NSW", suburb: "Camperdown", website: "https://www.sydney.edu.au/museum/", instagram: "@ccwm_sydney", latitude: -33.8853, longitude: 151.1905, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Entrance_to_the_Chau_Chak_Wing_Museum_April_2021.jpg?width=1600' },
  { id: "v-fairfield-city-museum-gallery", name: "Fairfield City Museum & Gallery", slug: "fairfield-city-museum-gallery", type: "museum", address: "634 The Horsley Drive, Smithfield NSW", suburb: "Smithfield", website: "https://www.fcmg.nsw.gov.au", instagram: "@fairfieldcitymuseumgallery", latitude: -33.8481, longitude: 150.9427, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-museum-of-sydney", founded_year: null, free_entry: true, entry_checked: "2026-07-22", name: "Museum of Sydney", slug: "museum-of-sydney", type: "museum", address: "Cnr Phillip & Bridge Streets, Sydney NSW", suburb: "Sydney", website: "https://mhnsw.au/visit-us/museum-of-sydney/", instagram: "@museumsofhistorynsw", latitude: -33.8636, longitude: 151.2114, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Museum_of_Sydney_2010.jpg?width=1600' },
  { id: "v-powerhouse-parramatta", name: "Powerhouse Parramatta", slug: "powerhouse-parramatta", type: "museum", address: "34 Phillip Street, Parramatta NSW", suburb: "Parramatta", website: "https://powerhouse.com.au/visit/parramatta", instagram: "@powerhousemuseum", latitude: -33.81, longitude: 151.0044, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-sydney-jewish-museum", founded_year: 1992, free_entry: false, entry_checked: "2026-07-22", name: "Sydney Jewish Museum", slug: "sydney-jewish-museum", type: "museum", address: "148 Darlinghurst Road, Darlinghurst NSW", suburb: "Darlinghurst", website: "https://sydneyjewishmuseum.com.au", instagram: "@sydneyjewishmuseum", latitude: -33.879, longitude: 151.2203, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Sydney_Jewish_Museum_Darlinghurst_Road_-_Burton_Street_junction_view.jpg?width=1600' },
  { id: "v-white-rabbit-gallery", opening_hours: 'Wed–Sun 10:00–17:00', hours_checked: '2026-07-21', name: "White Rabbit Gallery", slug: "white-rabbit-gallery", type: "museum", address: "30 Balfour Street, Chippendale NSW", suburb: "Chippendale", website: "https://whiterabbitcollection.org", instagram: "@whiterabbitgallery", latitude: -33.8865, longitude: 151.2003, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/White_Rabbit_Gallery_tea_house.jpg?width=1600' },
  { id: "v-cement-fondu", name: "Cement Fondu", slug: "cement-fondu", type: "gallery", address: "36 Gosbell Street, Paddington NSW", suburb: "Paddington", website: "https://cementfondu.org", instagram: "@cementfondu", latitude: -33.8776, longitude: 151.2222, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: true, image_url: null },
  { id: "v-vermilion-art", name: "Vermilion Art", slug: "vermilion-art", type: "gallery", address: "16 Hickson Road, Dawes Point NSW", suburb: "Dawes Point", website: "https://www.vermilionart.com.au", instagram: null, latitude: -33.8563, longitude: 151.2044, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-107-projects", name: "107 Projects", slug: "107-projects", type: "ari", address: "107 Redfern Street, Redfern NSW", suburb: "Redfern", website: "https://107.org.au", instagram: "@107projects", latitude: -33.8925, longitude: 151.2044, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-australian-design-centre", name: "Australian Design Centre", slug: "australian-design-centre", type: "gallery", address: "101–115 William Street, Darlinghurst NSW", suburb: "Darlinghurst", website: "https://australiandesigncentre.com", instagram: "@austdesigncentre", latitude: -33.8755, longitude: 151.2166, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: true, image_url: null },
  { id: "v-galerie-pompom", name: "Galerie pompom", slug: "galerie-pompom", type: "gallery", address: "2/39 Abercrombie Street, Chippendale NSW", suburb: "Chippendale", website: "https://galeriepompom.com", instagram: "@galeriepompom", latitude: -33.8877, longitude: 151.1984, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: true, image_url: null },
  { id: "v-artereal-gallery", name: "Artereal Gallery", slug: "artereal-gallery", type: "gallery", address: "747 Darling Street, Rozelle NSW", suburb: "Rozelle", website: "https://artereal.com.au", instagram: "@arterealgallery", latitude: -33.8614, longitude: 151.171, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-defiance-gallery", name: "Defiance Gallery", slug: "defiance-gallery", type: "gallery", address: "47 Enmore Road, Newtown NSW", suburb: "Newtown", website: "https://www.defiancegallery.com", instagram: "@defiancegallery", latitude: -33.899, longitude: 151.177, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-gallery-9", name: "Gallery 9", slug: "gallery-9", type: "gallery", address: "9 Darley Street, Darlinghurst NSW", suburb: "Darlinghurst", website: "https://www.gallery9.com.au", instagram: null, latitude: -33.883, longitude: 151.217, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-incinerator-art-space", name: "Incinerator Art Space", slug: "incinerator-art-space", type: "gallery", address: "2 Small Street, Willoughby NSW", suburb: "Willoughby", website: "https://www.willoughby.nsw.gov.au/community/community-spaces/incinerator-art-space", instagram: null, latitude: -33.803, longitude: 151.19, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: true, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/(1)Griffin_incinerator_Willoughby_123.jpg?width=1600' },
  { id: "v-delmar-gallery", name: "Delmar Gallery", slug: "delmar-gallery", type: "gallery", address: "144 Victoria Street, Ashfield NSW", suburb: "Ashfield", website: "https://www.trinity.nsw.edu.au/community/delmar-gallery/", instagram: "@delmargallery", latitude: -33.883, longitude: 151.125, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-woollahra-gallery", name: "Woollahra Gallery at Redleaf", slug: "woollahra-gallery-at-redleaf", type: "gallery", address: "548 New South Head Road, Double Bay NSW", suburb: "Double Bay", website: "https://www.woollahra.nsw.gov.au/woollahragallery", instagram: "@woollahragallery", latitude: -33.877, longitude: 151.245, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Double_Bay_Council_Chambers-A.jpg?width=1600' },
  { id: "v-16albermarle", name: "16albermarle Project Space", slug: "16albermarle", type: "gallery", address: "16 Albermarle Street, Newtown NSW", suburb: "Newtown", website: "https://www.16albermarle.com", instagram: "@16albermarleprojectspace", latitude: -33.898, longitude: 151.181, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null },
  { id: "v-hyde-park-barracks", founded_year: null, free_entry: true, entry_checked: "2026-07-22", name: "Hyde Park Barracks", slug: "hyde-park-barracks", type: "museum", address: null, suburb: "Sydney", website: "https://mhnsw.au", instagram: "@museumsofhistorynsw", latitude: -33.8712, longitude: 151.2124, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/HydeParkBarracks.JPG?width=1600', category: "institution", tier: "1", editorial_note: "UNESCO-listed convict barracks on Macquarie Street." },
  { id: "v-justice-police-museum", name: "Justice & Police Museum", slug: "justice-police-museum", type: "museum", address: null, suburb: "Sydney", website: "https://mhnsw.au", instagram: "@museumsofhistorynsw", latitude: -33.8623, longitude: 151.2119, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Justice_and_Police_Museum.jpg?width=1600', category: "institution", tier: "1", editorial_note: "Forensic photography and crime history in the old water police court - weekends only." },
  { id: "v-state-library-of-nsw-galleries", name: "State Library of NSW Galleries", slug: "state-library-of-nsw-galleries", type: "museum", address: null, suburb: "Sydney", website: "https://www.sl.nsw.gov.au", instagram: "@statelibrarynsw", latitude: -33.8668, longitude: 151.213, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/State_Library_of_New_South_Wales.jpg?width=1600', category: "institution", tier: "1", editorial_note: "Underrated free exhibitions from the state collection." },
  { id: "v-brett-whiteley-studio", name: "Brett Whiteley Studio", slug: "brett-whiteley-studio", type: "museum", address: null, suburb: "Surry Hills", website: "https://www.brettwhiteley.org/", instagram: "@brettwhiteleystudio", latitude: -33.8845, longitude: 151.2153, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Brett_whiteley_studio_raper_street_surry_hills.jpg?width=1600', category: "institution", tier: "1", editorial_note: "Whiteley's studio kept as he left it, run by the Art Gallery of NSW." },
  { id: "v-australian-national-maritime-museum", founded_year: 1991, free_entry: true, entry_checked: "2026-07-22", name: "Australian National Maritime Museum", slug: "australian-national-maritime-museum", type: "museum", address: null, suburb: "Darling Harbour", website: "https://www.sea.museum", instagram: "@sea.museum", latitude: -33.869, longitude: 151.1985, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Australian_National_Maritime_Museum_(30581601062).jpg?width=1600', category: "institution", tier: "1", editorial_note: "Wildlife Photographer of the Year among the masts." },
  { id: "v-customs-house", name: "Customs House", slug: "customs-house", type: "gallery", address: null, suburb: "Sydney", website: "https://www.sydneycustomshouse.com.au/", instagram: null, latitude: -33.8623, longitude: 151.2107, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Customs_House_(James_Barnet)%2C_Sydney_-_Wiki0055.jpg?width=1600', category: "institution", tier: "1", editorial_note: "Free City of Sydney exhibitions opposite Circular Quay." },
  { id: "v-rose-seidler-house", name: "Rose Seidler House", slug: "rose-seidler-house", type: "museum", address: null, suburb: "Wahroonga", website: "https://mhnsw.au", instagram: "@museumsofhistorynsw", latitude: -33.7275, longitude: 151.1092, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Rose_Seidler_House%2C_Wahroonga%2C_Sydney%2C_1951_-_photographed_by_Marcel_Seidler_(3461484773).jpg?width=1600', category: "institution", tier: "1b", editorial_note: "Harry Seidler's mid-century masterpiece; home of the Fifties Fair." },
  { id: "v-vaucluse-house", name: "Vaucluse House", slug: "vaucluse-house", type: "museum", address: null, suburb: "Vaucluse", website: "https://mhnsw.au", instagram: "@estatevauclusehouse", latitude: -33.8554, longitude: 151.278, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/130_Vaucluse_House%2C_Sydney%2C_1979_(52068393355).jpg?width=1600', category: "institution", tier: "1b", editorial_note: "Colonial estate with intact interiors and gardens." },
  { id: "v-elizabeth-bay-house", name: "Elizabeth Bay House", slug: "elizabeth-bay-house", type: "museum", address: null, suburb: "Elizabeth Bay", website: "https://mhnsw.au", instagram: "@museumsofhistorynsw", latitude: -33.8702, longitude: 151.2262, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "institution", tier: "1b", editorial_note: "'The finest house in the colony' - an architecture icon." },
  { id: "v-old-government-house", name: "Old Government House", slug: "old-government-house", type: "museum", address: null, suburb: "Parramatta", website: "https://www.nationaltrust.org.au/places/old-government-house/", instagram: null, latitude: -33.811, longitude: 150.999, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Old_Government_House_-_Parramatta_Park%2C_Parramatta%2C_NSW_(7822320214).jpg?width=1600', category: "institution", tier: "1b", editorial_note: "Australia's oldest public building, in Parramatta Park." },
  { id: "v-nutcote-may-gibbs-house", name: "Nutcote (May Gibbs' House)", slug: "nutcote-may-gibbs-house", type: "museum", address: null, suburb: "Neutral Bay", website: null, instagram: null, latitude: -33.839, longitude: 151.222, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "institution", tier: "1b", editorial_note: "The illustrator of the gumnut babies, at home." },
  { id: "v-macquarie-university-art-gallery", name: "Macquarie University Art Gallery", slug: "macquarie-university-art-gallery", type: "gallery", address: null, suburb: "Macquarie Park", website: "https://www.mq.edu.au/about/facilities/museums-collections/macquarie-university-art-gallery", instagram: null, latitude: -33.777, longitude: 151.113, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "public", tier: "2", editorial_note: "University collection and program on the north side." },
  { id: "v-margaret-whitlam-galleries", name: "Margaret Whitlam Galleries", slug: "margaret-whitlam-galleries", type: "gallery", address: null, suburb: "Parramatta", website: "https://www.whitlam.org/mwg", instagram: null, latitude: -33.818, longitude: 151.023, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "public", tier: "2", editorial_note: "Western Sydney University galleries in the Female Orphan School." },
  { id: "v-the-cross-art-projects", name: "The Cross Art Projects", slug: "the-cross-art-projects", type: "gallery", address: null, suburb: "Kings Cross", website: "https://www.crossart.com.au/", instagram: "@thecrossartprojects", latitude: -33.874, longitude: 151.2225, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "public", tier: "2", editorial_note: "Small curatorial non-profit with a political edge." },
  { id: "v-bondi-pavilion-gallery", name: "Bondi Pavilion Gallery", slug: "bondi-pavilion-gallery", type: "gallery", address: null, suburb: "Bondi Beach", website: "https://www.bondipavilion.com.au/discover/creative_spaces/art_gallery", instagram: "@bondipavilionofficial", latitude: -33.891, longitude: 151.276, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bondi_Beach_Pavilion.jpg?width=1600', category: "public", tier: "2", editorial_note: "Waverley Council's gallery in the restored beachfront pavilion." },
  { id: "v-art-space-on-the-concourse", name: "Art Space on The Concourse", slug: "art-space-on-the-concourse", type: "gallery", address: null, suburb: "Chatswood", website: "https://www.willoughby.nsw.gov.au/Council/Venues/Art-Space-Gallery-The-Concourse", instagram: null, latitude: -33.796, longitude: 151.183, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "public", tier: "2", editorial_note: "Willoughby Council's exhibition space on the North Shore." },
  { id: "v-juniper-hall", name: "Juniper Hall", slug: "juniper-hall", type: "gallery", address: null, suburb: "Paddington", website: "https://moranarts.org.au/galleries/", instagram: null, latitude: -33.884, longitude: 151.227, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "public", tier: "2", editorial_note: "Georgian landmark, home of the Moran Prizes." },
  { id: "v-artbank", name: "Artbank", slug: "artbank", type: "gallery", address: null, suburb: "Waterloo", website: "https://www.artbank.gov.au/", instagram: "@artbankau", latitude: -33.9, longitude: 151.207, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "public", tier: "2", editorial_note: "The government's lending collection - occasional public program." },
  { id: "v-blacktown-arts", name: "Blacktown Arts", slug: "blacktown-arts", type: "gallery", address: null, suburb: "Blacktown", website: null, instagram: null, latitude: -33.771, longitude: 150.906, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: true, image_url: null, category: "public", tier: "2b", editorial_note: "First Nations and Western Sydney focus in the Leo Kelly Centre." },
  { id: "v-parramatta-artists-studios", name: "Parramatta Artists' Studios", slug: "parramatta-artists-studios", type: "ari", address: null, suburb: "Parramatta", website: null, instagram: null, latitude: -33.815, longitude: 151.005, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "public", tier: "2b", editorial_note: "Council studios with open-studio nights." },
  { id: "v-hawkesbury-regional-gallery", name: "Hawkesbury Regional Gallery", slug: "hawkesbury-regional-gallery", type: "gallery", address: null, suburb: "Windsor", website: "https://www.hawkesbury.nsw.gov.au/gallery", instagram: "@hawkesburyregional_gallery", latitude: -33.613, longitude: 150.814, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "public", tier: "2b", editorial_note: "Regional gallery on Sydney's north-west edge." },
  { id: "v-hurstville-museum-gallery", name: "Hurstville Museum & Gallery", slug: "hurstville-museum-gallery", type: "museum", address: null, suburb: "Hurstville", website: "https://www.georgesriver.nsw.gov.au/Community/Art-and-Culture/Hurstville-Museum-Gallery", instagram: "@hurstvillemuseumgallery", latitude: -33.967, longitude: 151.103, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "public", tier: "2b", editorial_note: "Georges River Council museum and gallery." },
  { id: "v-peacock-gallery", name: "Peacock Gallery", slug: "peacock-gallery", type: "gallery", address: null, suburb: "Auburn", website: "https://www.cumberland.nsw.gov.au/peacock-gallery", instagram: null, latitude: -33.853, longitude: 151.028, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "public", tier: "2b", editorial_note: "Small gallery in the Auburn Botanic Gardens." },
  { id: "v-museums-discovery-centre", name: "Museums Discovery Centre", slug: "museums-discovery-centre", type: "museum", address: null, suburb: "Castle Hill", website: "https://powerhouse.com.au/visit/castle-hill", instagram: null, latitude: -33.732, longitude: 150.98, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "public", tier: "2b", editorial_note: "The Powerhouse's open store - tours through the collection." },
  { id: "v-sarah-cottier-gallery", name: "Sarah Cottier Gallery", slug: "sarah-cottier-gallery", type: "gallery", address: null, suburb: "Paddington", website: null, instagram: null, latitude: -33.884, longitude: 151.226, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: true, image_url: null, category: "commercial", tier: "3", editorial_note: "Minimal and conceptual since the nineties." },
  { id: "v-the-commercial", name: "The Commercial", slug: "the-commercial", type: "gallery", address: null, suburb: "Marrickville", website: "https://www.thecommercialgallery.com/", instagram: null, latitude: -33.911, longitude: 151.155, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3", editorial_note: "Sharp conceptual program with a devoted following." },
  { id: "v-wagner-contemporary", name: "Wagner Contemporary", slug: "wagner-contemporary", type: "gallery", address: null, suburb: "Paddington", website: "https://wagnercontemporary.com.au/", instagram: "@wagnercontemporary", latitude: -33.885, longitude: 151.227, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3", editorial_note: "Approachable contemporary painting on Oxford Street." },
  { id: "v-piermarq", name: "Piermarq", slug: "piermarq", type: "gallery", address: null, suburb: "Paddington", website: "https://www.piermarq.com.au/", instagram: "@piermarqart", latitude: -33.884, longitude: 151.225, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3", editorial_note: "International program pitched at a younger crowd." },
  { id: "v-gallery-sally-dan-cuthbert", name: "Gallery Sally Dan-Cuthbert", slug: "gallery-sally-dan-cuthbert", type: "gallery", address: null, suburb: "Rushcutters Bay", website: "https://gallerysallydancuthbert.com/", instagram: "@gallerysallydancuthbert", latitude: -33.875, longitude: 151.225, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3", editorial_note: "Art crossed with collectible design." },
  { id: "v-annette-larkin-fine-art", name: "Annette Larkin Fine Art", slug: "annette-larkin-fine-art", type: "gallery", address: null, suburb: "Darlinghurst", website: "https://annettelarkin.com/", instagram: "@annettelarkinfineart", latitude: -33.879, longitude: 151.217, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3", editorial_note: "Secondary-market specialist." },
  { id: "v-maunsell-wickes", name: "Maunsell Wickes", slug: "maunsell-wickes", type: "gallery", address: null, suburb: "Paddington", website: "https://maunsellwickes.com/", instagram: "@maunsellwickesgallery", latitude: -33.885, longitude: 151.224, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3", editorial_note: "Long-established rooms on Glenmore Road." },
  { id: "v-richard-martin-art", name: "Richard Martin Art", slug: "richard-martin-art", type: "gallery", address: null, suburb: "Woollahra", website: "https://www.richardmartinart.com.au/", instagram: null, latitude: -33.888, longitude: 151.24, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3", editorial_note: "Modern and contemporary secondary market." },
  { id: "v-harvey-galleries", name: "Harvey Galleries", slug: "harvey-galleries", type: "gallery", address: null, suburb: "Mosman", website: "https://harveygalleries.com.au/", instagram: "@harveygalleries", latitude: -33.828, longitude: 151.244, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3", editorial_note: "Commercial stalwart with harbourside clientele." },
  { id: "v-wentworth-galleries", name: "Wentworth Galleries", slug: "wentworth-galleries", type: "gallery", address: null, suburb: "Sydney", website: null, instagram: null, latitude: -33.868, longitude: 151.211, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3", editorial_note: "CBD commercial gallery." },
  { id: "v-jerico-contemporary", name: "Jerico Contemporary", slug: "jerico-contemporary", type: "gallery", address: null, suburb: "Woolloomooloo", website: "http://www.jericocontemporary.com/", instagram: "@jerico_contemporary", latitude: -33.87, longitude: 151.22, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3b", editorial_note: "Young and elegant, by the finger wharf." },
  { id: "v-m-contemporary", name: "M Contemporary", slug: "m-contemporary", type: "gallery", address: null, suburb: "Woollahra", website: "https://mcontemp.com/", instagram: "@mcontemporary", latitude: -33.885, longitude: 151.24, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3b", editorial_note: "Strong curation on Ocean Street." },
  { id: "v-stanley-street-gallery", name: "Stanley Street Gallery", slug: "stanley-street-gallery", type: "gallery", address: null, suburb: "Darlinghurst", website: "https://stanleystreetgallery.com.au/", instagram: "@stanley_street_gallery", latitude: -33.878, longitude: 151.218, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3b", editorial_note: "Contemporary art and studio jewellery." },
  { id: "v-curatorial-co", name: "Curatorial+Co", slug: "curatorial-co", type: "gallery", address: null, suburb: "Redfern", website: "https://curatorialandco.com", instagram: "@curatorialandco", latitude: -33.892, longitude: 151.204, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3b", editorial_note: "Online-first gallery with a physical space." },
  { id: "v-flinders-street-gallery", name: "Flinders Street Gallery", slug: "flinders-street-gallery", type: "gallery", address: null, suburb: "Surry Hills", website: "https://www.flindersstreetgallery.com", instagram: "@flindersstgallery", latitude: -33.886, longitude: 151.214, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3b", editorial_note: "Painting-focused program." },
  { id: "v-black-eye-gallery", name: "Black Eye Gallery", slug: "black-eye-gallery", type: "gallery", address: null, suburb: "Darlinghurst", website: "https://blackeyegallery.com.au", instagram: "@blackeyegallery", latitude: -33.879, longitude: 151.218, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3b", editorial_note: "Photography specialist." },
  { id: "v-gaffa-gallery", name: "Gaffa Gallery", slug: "gaffa-gallery", type: "gallery", address: null, suburb: "Sydney", website: "https://www.gaffa.com.au", instagram: "@gaffagallery", latitude: -33.876, longitude: 151.207, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3b", editorial_note: "Craft and photography across two floors." },
  { id: "v-sabbia-gallery", name: "Sabbia Gallery", slug: "sabbia-gallery", type: "gallery", address: null, suburb: "Redfern", website: "https://sabbiagallery.com", instagram: "@sabbiagallery", latitude: -33.893, longitude: 151.205, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3b", editorial_note: "Glass and ceramics at the highest level." },
  { id: "v-ambush-gallery", name: "Ambush Gallery", slug: "ambush-gallery", type: "gallery", address: null, suburb: "Chippendale", website: "https://ambushgallery.com", instagram: "@ambushgallery", latitude: -33.887, longitude: 151.2, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3b", editorial_note: "Street-leaning contemporary at Central Park." },
  { id: "v-traffic-jam-galleries", name: "Traffic Jam Galleries", slug: "traffic-jam-galleries", type: "gallery", address: null, suburb: "Neutral Bay", website: "https://trafficjamgalleries.com", instagram: "@trafficjamgalleries", latitude: -33.832, longitude: 151.218, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3b", editorial_note: "Lower North Shore contemporary." },
  { id: "v-art2muse", name: "Art2Muse", slug: "art2muse", type: "gallery", address: null, suburb: "Double Bay", website: "https://art2muse.com.au", instagram: "@art2muse", latitude: -33.877, longitude: 151.243, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3b", editorial_note: "Eastern-suburbs contemporary." },
  { id: "v-studio-gallery", name: "Studio Gallery", slug: "studio-gallery", type: "gallery", address: null, suburb: "Waterloo", website: null, instagram: "@studiogallerygroup", latitude: -33.9, longitude: 151.206, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3b", editorial_note: "Melbourne group with a Sydney room." },
  { id: "v-badger-fox-gallery", name: "Badger & Fox Gallery", slug: "badger-fox-gallery", type: "gallery", address: null, suburb: "Surry Hills", website: "https://badgerandfoxgallery.com", instagram: "@badfox201", latitude: -33.886, longitude: 151.212, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3b", editorial_note: "Contemporary rooms off Crown Street." },
  { id: "v-goodspace", name: "Goodspace", slug: "goodspace", type: "gallery", address: null, suburb: "Chippendale", website: null, instagram: "@goodspacegallery", latitude: -33.887, longitude: 151.199, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "commercial", tier: "3b", editorial_note: "Young, fast-moving program." },
  { id: "v-sno-contemporary-art-projects", name: "SNO Contemporary Art Projects", slug: "sno-contemporary-art-projects", type: "ari", address: null, suburb: "Marrickville", website: "http://www.sno.org.au", instagram: null, latitude: -33.907, longitude: 151.156, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "ari", tier: "4", editorial_note: "Non-objective art, uncompromising." },
  { id: "v-knulp", name: "Knulp", slug: "knulp", type: "ari", address: null, suburb: "Sydney", website: "http://www.knulps.org", instagram: "@knulpknulpknulp", latitude: -33.89, longitude: 151.19, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "ari", tier: "4", editorial_note: "Tiny, deeply insider artist-run space." },
  { id: "v-harrington-street-gallery", name: "Harrington Street Gallery", slug: "harrington-street-gallery", type: "ari", address: null, suburb: "Chippendale", website: "http://www.harringtonstreetgallery.com", instagram: "@theharringtonstreetartscentre", latitude: -33.887, longitude: 151.198, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "ari", tier: "4", editorial_note: "Sydney's oldest artists' co-operative." },
  { id: "v-art-leven", name: "Art Leven", slug: "art-leven", type: "gallery", address: null, suburb: "Redfern", website: "https://www.cooeeart.com.au", instagram: "@art.leven", latitude: -33.893, longitude: 151.204, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "first_nations", tier: "3", editorial_note: "The oldest specialist First Nations gallery, formerly Cooee Art." },
  { id: "v-kate-owen-gallery", name: "Kate Owen Gallery", slug: "kate-owen-gallery", type: "gallery", address: null, suburb: "Rozelle", website: "https://www.kateowengallery.com", instagram: "@kateowengallery", latitude: -33.861, longitude: 151.171, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "first_nations", tier: "3", editorial_note: "Three floors of Aboriginal art." },
  { id: "v-aboriginal-contemporary", name: "Aboriginal Contemporary", slug: "aboriginal-contemporary", type: "gallery", address: null, suburb: "Bronte", website: "https://www.aboriginalcontemporary.com.au", instagram: "@aboriginal.contemporary", latitude: -33.905, longitude: 151.264, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "first_nations", tier: "3", editorial_note: "Community-sourced work from the deserts and the Top End." },
  { id: "v-gannon-house-gallery", name: "Gannon House Gallery", slug: "gannon-house-gallery", type: "gallery", address: null, suburb: "The Rocks", website: "https://gannonhousegallery.com/", instagram: "@gannonhouse", latitude: -33.859, longitude: 151.209, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "first_nations", tier: "3", editorial_note: "Aboriginal and Australian art in The Rocks." },
  { id: "v-spirit-gallery", name: "Spirit Gallery", slug: "spirit-gallery", type: "gallery", address: null, suburb: "The Rocks", website: "https://www.spiritgallery.com.au/", instagram: null, latitude: -33.859, longitude: 151.209, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "first_nations", tier: "3", editorial_note: "Accessible First Nations art and objects." },
  { id: "v-apy-gallery", name: "APY Gallery", slug: "apy-gallery", type: "gallery", address: null, suburb: "Darlinghurst", website: "https://www.apygallery.com/", instagram: null, latitude: -33.879, longitude: 151.217, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "first_nations", tier: "3", editorial_note: "Artist-owned gallery of the APY Lands studios." },
  { id: "v-d-lan-contemporary", name: "D'Lan Contemporary", slug: "d-lan-contemporary", type: "gallery", address: null, suburb: "Sydney", website: null, instagram: null, latitude: -33.87, longitude: 151.21, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "first_nations", tier: "3", editorial_note: "Blue-chip secondary market for First Nations masters." },
  { id: "v-wollongong-art-gallery", name: "Wollongong Art Gallery", slug: "wollongong-art-gallery", type: "gallery", address: null, suburb: "Wollongong", website: "https://wollongongartgallery.au", instagram: "@wollongongartgallery", latitude: -34.424, longitude: 150.893, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Wollongong_Art_Gallery_August_2020.jpg?width=1600', category: "day_trip", tier: "2", editorial_note: "The largest regional gallery south of Sydney." },
  { id: "v-ngununggula", name: "Ngununggula", slug: "ngununggula", type: "gallery", address: null, suburb: "Bowral", website: "https://ngununggula.com", instagram: "@ngununggula", latitude: -34.478, longitude: 150.42, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "day_trip", tier: "2", editorial_note: "Southern Highlands regional with a sharp program." },
  { id: "v-bundanon", name: "Bundanon", slug: "bundanon", type: "museum", address: null, suburb: "Illaroo", website: "https://www.bundanon.com.au", instagram: "@bundanontrust", latitude: -34.85, longitude: 150.51, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "day_trip", tier: "1", editorial_note: "Arthur Boyd's gift - art museum and the Kerstin Thompson bridge in the bush." },
  { id: "v-blue-mountains-cultural-centre", name: "Blue Mountains Cultural Centre", slug: "blue-mountains-cultural-centre", type: "gallery", address: null, suburb: "Katoomba", website: "https://bluemountainsculturalcentre.com.au", instagram: "@bluemountainsculturalcentre", latitude: -33.712, longitude: 150.312, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "day_trip", tier: "2", editorial_note: "Regional gallery with an escarpment view." },
  { id: "v-newcastle-art-gallery", name: "Newcastle Art Gallery", slug: "newcastle-art-gallery", type: "gallery", address: null, suburb: "Newcastle", website: "https://newcastleartgallery.nsw.gov.au", instagram: "@newcastleartgalleryaustralia", latitude: -32.928, longitude: 151.771, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Newcastle_Art_Gallery%2C_April_2026.jpg?width=1600', category: "day_trip", tier: "2", editorial_note: "Reopened after a major expansion." },
  { id: "v-the-lock-up", name: "The Lock-Up", slug: "the-lock-up", type: "gallery", address: null, suburb: "Newcastle", website: "https://thelockup.org.au", instagram: "@thelockupartspace", latitude: -32.927, longitude: 151.779, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "day_trip", tier: "2", editorial_note: "Contemporary art in the old police lock-up." },
  { id: "v-maitland-regional-art-gallery", name: "Maitland Regional Art Gallery", slug: "maitland-regional-art-gallery", type: "gallery", address: null, suburb: "Maitland", website: "https://www.mrag.org.au", instagram: "@maitlandregionalartgallery", latitude: -32.733, longitude: 151.557, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: 'https://commons.wikimedia.org/wiki/Special:FilePath/Maitland_Regional_Art_Gallery%2C_December_2025_02.jpg?width=1600', category: "day_trip", tier: "2", editorial_note: "Hunter Valley regional with generous programming." },
  { id: "v-gosford-regional-gallery", name: "Gosford Regional Gallery", slug: "gosford-regional-gallery", type: "gallery", address: null, suburb: "Gosford", website: "https://gosfordregionalgallery.com", instagram: "@gosfordregionalgallery", latitude: -33.426, longitude: 151.342, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "day_trip", tier: "2", editorial_note: "Central Coast gallery with the Edogawa garden." },
  { id: "v-smith-singer", name: "Smith & Singer", slug: "smith-singer", type: "gallery", address: null, suburb: "Sydney", website: "https://www.smithandsinger.com.au", instagram: "@smith_singer", latitude: -33.869, longitude: 151.21, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "auction", tier: "3", editorial_note: "Sotheby's-licensed auction house." },
  { id: "v-deutscher-and-hackett", name: "Deutscher and Hackett", slug: "deutscher-and-hackett", type: "gallery", address: null, suburb: "Paddington", website: "https://www.deutscherandhackett.com", instagram: "@deutscherandhackett", latitude: -33.884, longitude: 151.226, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "auction", tier: "3", editorial_note: "Major Australian art auctions." },
  { id: "v-menzies", name: "Menzies", slug: "menzies", type: "gallery", address: null, suburb: "Kensington", website: "https://www.menziesartbrands.com", instagram: "@menziesauctions", latitude: -33.92, longitude: 151.222, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "auction", tier: "3", editorial_note: "Australian and international art auctions." },
  { id: "v-shapiro-auctioneers", name: "Shapiro Auctioneers", slug: "shapiro-auctioneers", type: "gallery", address: null, suburb: "Woollahra", website: "https://www.shapiro.com.au", instagram: "@shapirosydney", latitude: -33.888, longitude: 151.24, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "auction", tier: "3", editorial_note: "Art, design and decorative arts." },
  { id: "v-bonhams-australia", name: "Bonhams Australia", slug: "bonhams-australia", type: "gallery", address: null, suburb: "Double Bay", website: "https://www.bonhams.com/location/SYD/sydney/", instagram: "@bonhams1793", latitude: -33.877, longitude: 151.243, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "auction", tier: "3", editorial_note: "International house, Australian salerooms." },
  { id: "v-leonard-joel-sydney", name: "Leonard Joel Sydney", slug: "leonard-joel-sydney", type: "gallery", address: null, suburb: "Woollahra", website: "https://www.leonardjoel.com.au", instagram: "@leonardjoelauctions", latitude: -33.888, longitude: 151.24, city: "Sydney", owner_user_id: null, is_claimed: false, is_fixture: false, image_url: null, category: "auction", tier: "3", editorial_note: "Auctions across art and objects." },
];

export const SEED_EXHIBITIONS: Exhibition[] = [
  {
    id: 'e-archibald',
    venue_id: 'v-agnsw',
    title: 'Archibald, Wynne & Sulman Prizes 2026',
    artists: 'Finalists 2026',
    start_date: '2026-05-09',
    end_date: '2026-08-16',
    opening_datetime: null,
    description:
      'Australia’s most argued-over walls. The Archibald’s portraits, the Wynne’s landscapes and the Sulman’s subject pictures hang side by side — a yearly census of who we are and how we want to be seen.',
    image_url: 'asset:archibald',
    status: 'approved',
    rejection_reason: null,
    is_featured: true,
    city: 'Sydney',
  },
  {
    id: 'e-murakami',
    venue_id: 'v-agnsw',
    title: 'Takashi Murakami',
    artists: 'Takashi Murakami',
    start_date: '2026-12-05',
    end_date: '2027-07-18',
    opening_datetime: null,
    description:
      'The superflat universe at full scale — smiling flowers, silver screens and centuries of Japanese painting compressed into one relentless surface. Murakami’s first major Sydney survey.',
    image_url: 'https://upload.wikimedia.org/wikipedia/commons/8/80/Takashi_Murakami_at_Versailles_Sept._2010_%281%29.jpg',
    status: 'approved',
    rejection_reason: null,
    is_featured: true,
    city: 'Sydney',
  },
  {
    id: 'e-primavera',
    venue_id: 'v-mca',
    title: 'Primavera 2026: Young Australian Artists',
    artists: 'Young Australian Artists',
    start_date: '2026-06-27',
    end_date: '2026-09-28',
    opening_datetime: null,
    description:
      'The MCA’s annual exhibition of Australian artists aged 35 and under — the clearest early signal of where Australian art is going next.',
    image_url: 'asset:primavera',
    status: 'approved',
    rejection_reason: null,
    is_featured: true,
    city: 'Sydney',
  },
  {
    id: 'e-armanious',
    venue_id: 'v-mca',
    title: 'Hany Armanious: The Planets',
    artists: 'Hany Armanious',
    start_date: '2026-07-10',
    end_date: '2026-10-26',
    opening_datetime: null,
    description:
      'Casts of the overlooked — foam, wax, candle stubs, offcuts — remade with such fidelity that the ordinary turns uncanny. A survey of one of Australia’s most quietly influential sculptors.',
    image_url: 'asset:armanious',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-kahukiwa',
    venue_id: 'v-mca',
    title: 'Robyn Kahukiwa: My Ancestors Are Always With Me',
    artists: 'Robyn Kahukiwa',
    start_date: '2026-10-14',
    end_date: '2027-02-07',
    opening_datetime: null,
    description:
      'Paintings that carry whakapapa like a current — the late Māori artist’s figures of women and ancestors, political and tender at once, gathered for Sydney audiences.',
    image_url: 'asset:kahukiwa',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-nell',
    venue_id: 'v-mca',
    title: 'Nell: Loti Smorgon Sculpture Terrace Commission',
    artists: 'Nell',
    start_date: '2026-08-26',
    end_date: '2027-08-23',
    opening_datetime: null,
    description:
      'A new commission by Nell — where rock’n’roll, Buddhism and the eucalypt meet. On the MCA’s public-facing spaces through spring.',
    image_url: 'asset:nell',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-constructed-world',
    venue_id: 'v-roslynoxley9',
    title: 'A Constructed World',
    artists: 'A Constructed World',
    start_date: '2026-06-26',
    end_date: '2026-07-18',
    opening_datetime: null,
    description:
      'The collaborative practice of Geoff Lowe and Jacqueline Riva — painting, performance and speech acts that keep meaning deliberately unstable.',
    image_url: 'asset:constructed-world',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-bennett',
    venue_id: 'v-cassandrabird',
    title: 'Places of Delight',
    artists: 'Robby Bennett',
    start_date: '2026-06-19',
    end_date: '2026-08-01',
    opening_datetime: null,
    description:
      'New paintings by Robby Bennett — gardens, rooms and remembered places rendered as sites of pleasure and slight unease.',
    image_url: 'asset:bennett',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-gabori-ledgerwood',
    venue_id: 'v-1301sw',
    title: 'Sally Gabori & Judy Ledgerwood',
    artists: 'Sally Gabori, Judy Ledgerwood',
    start_date: '2026-06-13',
    end_date: '2026-07-11',
    opening_datetime: null,
    description:
      'Two painters of colour at scale, an ocean apart — Gabori’s Kaiadilt country in saturated fields beside Ledgerwood’s rhythmic Chicago abstraction.',
    image_url: 'asset:gabori-ledgerwood',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-infinite-gesture',
    venue_id: 'v-amesyavuz',
    title: 'Infinite Gesture',
    artists: 'Group Exhibition',
    start_date: '2026-07-04',
    end_date: '2026-08-08',
    opening_datetime: null,
    description:
      'A group exhibition on the mark as a unit of thought — gesture repeated, extended and abstracted across painting and works on paper.',
    image_url: 'asset:infinite-gesture',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-crothers',
    venue_id: 'v-olsen',
    title: 'Interconnected',
    artists: 'Aaron Crothers',
    start_date: '2026-07-22',
    end_date: '2026-08-15',
    opening_datetime: '2026-07-22T18:00:00+10:00',
    description:
      'Aaron Crothers maps the systems beneath landscape — geology, weather, root and network — in paintings that read like aerial diagrams of connection.',
    image_url: 'asset:crothers',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-pulse',
    venue_id: 'v-gcs',
    title: 'Pulse',
    artists: 'Group Exhibition',
    start_date: '2026-06-12',
    end_date: '2026-07-11',
    opening_datetime: null,
    description:
      'Works that take rhythm as subject and method — repetition, beat and breath across media at the Grace Cossington Smith Gallery.',
    image_url: 'asset:pulse',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-abbotsleigh',
    venue_id: 'v-gcs',
    title: 'Abbotsleigh Biennial: Finalists',
    artists: 'Biennial Finalists',
    start_date: '2026-07-18',
    end_date: '2026-08-15',
    opening_datetime: '2026-07-18T14:00:00+10:00',
    description:
      'Finalists of the Abbotsleigh Biennial — a cross-section of current practice selected for the gallery’s biennial exhibition and prize.',
    image_url: 'asset:abbotsleigh',
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  // ---- verified July 2026 — sourced from the venues' own listings ----
  {
    id: 'e-black-myth',
    venue_id: 'v-white-rabbit-gallery',
    title: 'Black Myth',
    artists: 'White Rabbit Collection artists',
    start_date: '2026-06-25',
    end_date: '2026-11-08',
    opening_datetime: null,
    description:
      'Drawn from the Judith Neilson collection — new Chinese art that reaches for the mythic: gods, ghosts and machines tangled in one dark, spectacular sweep across all four floors.',
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: true,
    city: 'Sydney',
  },
  {
    id: 'e-nsw-fellowship',
    venue_id: 'v-artspace',
    title: '2026 NSW Visual Arts Fellowship (Emerging)',
    artists: 'Virginia Keft, Charles Levi, Tia Madden, Amelia Skelton, Sue Jo Wright, Natasha & Caitlin Dubler',
    start_date: '2026-07-03',
    end_date: '2026-09-06',
    opening_datetime: null,
    description:
      'Six emerging practices in one charged room — the state’s sharpest early-career artists make their case for the Fellowship at The Gunnery.',
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-undying',
    venue_id: 'v-chau-chak-wing-museum',
    title: 'Undying: Abdul-Rahman Abdullah',
    artists: 'Abdul-Rahman Abdullah',
    start_date: '2026-02-07',
    end_date: '2026-07-26',
    opening_datetime: null,
    description:
      'Hand-carved animals meet the museum’s natural history collection — Abdullah’s tender, uncanny menagerie on our entangled lives with the creatures we keep, fear and mourn.',
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-unkept',
    venue_id: 'v-chau-chak-wing-museum',
    title: 'Unkept: Kirtika Kain',
    artists: 'Kirtika Kain',
    start_date: '2026-02-07',
    end_date: '2026-07-26',
    opening_datetime: null,
    description:
      'In a makeshift storehouse in the Penelope Gallery, Kain works gold, tar and pigment into a reckoning with caste, labour and the histories archives fail to keep.',
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-salon-des-refuses',
    venue_id: 'v-sh-ervin-gallery',
    title: 'Salon des Refusés 2026',
    artists: 'The alternative Archibald & Wynne selection',
    start_date: '2026-05-09',
    end_date: '2026-07-26',
    opening_datetime: null,
    description:
      'The ones that got away — the annual alternative selection from the Archibald and Wynne entries, hung on Observatory Hill and argued over just as fiercely.',
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-mitch-cairns',
    venue_id: 'v-nas-gallery',
    title: 'Mitch Cairns: Artist’s Mouth',
    artists: 'Mitch Cairns',
    start_date: '2026-05-01',
    end_date: '2026-07-11',
    opening_datetime: null,
    description:
      'Twenty years of Cairns’ cool, exact painting — 48 works, the 2017 Archibald winner among them — surveyed in the old Darlinghurst Gaol where he trained.',
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-jasper-knight',
    venue_id: 'v-mosman-art-gallery',
    title: 'Jasper Knight: Collage, prints and works on paper',
    artists: 'Jasper Knight',
    start_date: '2026-06-01',
    end_date: '2026-08-09',
    opening_datetime: null,
    description:
      'Harbour light at speed — Knight’s cut, layered and printed Sydney, from ferries to pylons, in a survey of his works on paper at Mosman.',
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-tamara-dean',
    venue_id: 'v-manly-art-gallery-museum',
    title: 'Tamara Dean: Leave Only Footprints',
    artists: 'Tamara Dean',
    start_date: '2026-06-12',
    end_date: '2026-08-02',
    opening_datetime: null,
    description:
      'Bodies folded into bushland, ocean and storm — the first survey of Dean’s staged photomedia, where the human figure is one animal among many.',
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-min-wong',
    venue_id: 'v-manly-art-gallery-museum',
    title: 'Min Wong: You shall definitely pass',
    artists: 'Min Wong',
    start_date: '2026-06-12',
    end_date: '2026-08-02',
    opening_datetime: null,
    description:
      'Fresh from residencies in Berlin and Athens, Wong builds an immersive installation on power, belonging and the promises of self-improvement.',
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-chronos',
    venue_id: 'v-manly-art-gallery-museum',
    title: 'Chronos: Australian ceramics from 1933',
    artists: 'Australian ceramicists, 1933 to now',
    start_date: '2026-03-21',
    end_date: '2027-03-14',
    opening_datetime: null,
    description:
      'Nine decades of Australian clay — how ceramic practice holds and hands on cultural change, traced through the gallery’s collection.',
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-friends-annual',
    venue_id: 'v-campbelltown-arts-centre',
    title: 'Friends Annual & Focus: Zara Collins',
    artists: 'Friends of Campbelltown Arts Centre, Zara Collins',
    start_date: '2026-06-27',
    end_date: '2026-09-13',
    opening_datetime: null,
    description:
      'The region’s artists on their own walls — the Friends’ eclectic annual across styles and mediums, with Zara Collins as this year’s Focus artist.',
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-dorabialski',
    venue_id: 'v-firstdraft',
    title: 'You wouldn’t remember him',
    artists: 'Nina Dorabialski',
    start_date: '2026-07-18',
    end_date: '2026-08-22',
    opening_datetime: null,
    description:
      'The family album, present only by inference — Dorabialski circles the pictures never shown, unsettling the stories nuclear families tell about themselves.',
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-bartley',
    venue_id: 'v-king-street-gallery',
    title: 'The Quick and the Slow',
    artists: 'John Bartley',
    start_date: '2026-07-07',
    end_date: '2026-08-01',
    opening_datetime: null,
    description:
      'Bartley’s new paintings hold two speeds at once — quick marks over slow ground, landscape as something felt in tempo rather than seen in place.',
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: 'e-nhan',
    venue_id: 'v-king-street-gallery',
    title: 'Proverbial',
    artists: 'Nathan Nhan',
    start_date: '2026-07-07',
    end_date: '2026-08-01',
    opening_datetime: null,
    description:
      'Nhan takes the worn wisdom of proverbs and paints it strange again — inherited sayings tested against a first-generation present.',
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-caballero",
    venue_id: "v-wollongong-art-gallery",
    title: "Once Upon a Doll",
    artists: "Raquel Caballero",
    start_date: "2026-07-03",
    end_date: "2026-11-01",
    opening_datetime: null,
    description:
      "Sixteen hand-built dolls by Raquel Caballero \u2014 craft turned uncanny, childhood forms carrying very adult freight.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-banks",
    venue_id: "v-wollongong-art-gallery",
    title: "Popular Versus Culture",
    artists: "Georgia Banks",
    start_date: "2026-06-06",
    end_date: "2026-09-06",
    opening_datetime: null,
    description:
      "Made in the wake of a residency at The Andy Warhol Museum, Banks pushes Warhol's obsession with fame and fandom into the feed-scroll present.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-new-religion",
    venue_id: "v-ngununggula",
    title: "New Religion",
    artists: "Hayley Millar Baker, Nell, Julia Robinson, Brent Harris & others",
    start_date: "2026-06-27",
    end_date: "2026-10-18",
    opening_datetime: null,
    description:
      "Faith and its afterimages \u2014 contemporary work alongside loans from the AGNSW and NGA, from D\u00fcrer to now, on symbols that outlive belief.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-man-on-fire",
    venue_id: "v-bundanon",
    title: "Man on Fire: Visions of Nebuchadnezzar",
    artists: "Arthur Boyd, Shaun Gladwell",
    start_date: "2026-07-04",
    end_date: "2026-10-11",
    opening_datetime: null,
    description:
      "Boyd's Nebuchadnezzar paintings \u2014 a king burning through his own hubris \u2014 meet a major new Shaun Gladwell commission on the same unravelling.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: true,
    city: 'Sydney',
  },
  {
    id: "e-ksca",
    venue_id: "v-blue-mountains-cultural-centre",
    title: "The Art of Adaptation",
    artists: "Kandos School of Cultural Adaptation",
    start_date: "2026-06-20",
    end_date: "2026-08-02",
    opening_datetime: null,
    description:
      "The Kandos School of Cultural Adaptation brings its field-tested art-and-land experiments to Katoomba \u2014 practical, hopeful, unromantic.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-robinson",
    venue_id: "v-newcastle-art-gallery",
    title: "Brian Robinson: Multiverse",
    artists: "Brian Robinson",
    start_date: "2026-05-23",
    end_date: "2026-08-30",
    opening_datetime: null,
    description:
      "The Torres Strait Islander artist's first major NSW solo \u2014 monumental linocuts, larger-than-life sculpture and an immersive animation in the reopened gallery.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-tiyan-baker",
    venue_id: "v-newcastle-art-gallery",
    title: "Tiyan Baker",
    artists: "Tiyan Baker",
    start_date: "2026-07-25",
    end_date: "2026-09-06",
    opening_datetime: null,
    description:
      "Baker's first institutional solo, on home ground \u2014 part of the reopened Newcastle Art Gallery's statement 2026 program.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-sharpe",
    venue_id: "v-the-lock-up",
    title: "Into the Dark",
    artists: "Wendy Sharpe",
    start_date: "2026-07-18",
    end_date: "2026-09-13",
    opening_datetime: null,
    description:
      "Archibald winner Wendy Sharpe paints the night side \u2014 staged in the cells of a former police lock-up, which suits the work.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-20x20",
    venue_id: "v-gosford-regional-gallery",
    title: "20 x 20 Art Exhibition 2026",
    artists: "Central Coast artists, anonymous until sold",
    start_date: "2026-07-22",
    end_date: "2026-08-03",
    opening_datetime: null,
    description:
      "A wall of anonymous 20-centimetre squares at $100 each \u2014 the annual leveller where a name means nothing until the red dot goes up.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-confluence",
    venue_id: "v-gosford-regional-gallery",
    title: "Confluence",
    artists: "David Collins, Ana Pollak",
    start_date: "2026-07-25",
    end_date: "2026-09-13",
    opening_datetime: null,
    description:
      "Partners for forty years, Collins and Pollak hang side by side \u2014 two practices that meet the way rivers do, keeping their own currents.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-sydney-contemporary",
    venue_id: "v-carriageworks",
    title: "Sydney Contemporary 2026",
    artists: "100+ galleries, 500+ artists",
    start_date: "2026-09-03",
    end_date: "2026-09-06",
    opening_datetime: null,
    description:
      "The southern hemisphere's biggest art fair takes over the Eveleigh rail sheds \u2014 a hundred galleries, five hundred artists, four dense days.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-4a-30",
    venue_id: "v-4a-centre",
    title: "Archetypes: 30 Years of 4A",
    artists: "Asian-Australian artists across three decades",
    start_date: "2026-07-11",
    end_date: "2026-09-20",
    opening_datetime: null,
    description:
      "Three decades of Asian-Australian art and advocacy \u2014 new commissions hung against the archive that made them possible.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-olley",
    venue_id: "v-nas-gallery",
    title: "Margaret Olley: Australian Intimiste",
    artists: "Margaret Olley",
    start_date: "2026-07-31",
    end_date: "2026-10-25",
    opening_datetime: null,
    description:
      "Interiors, ranunculus, the unmade table \u2014 the National Art School honours its most beloved alum with a full survey of the great intimiste.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: true,
    city: 'Sydney',
  },
  {
    id: "e-jannides",
    venue_id: "v-hazelhurst-arts-centre",
    title: "Milli Jannides",
    artists: "Milli Jannides",
    start_date: "2026-07-04",
    end_date: "2026-08-30",
    opening_datetime: null,
    description:
      "Dreamlike, loose-limbed painting from the Sydney-born, Aotearoa-based Jannides \u2014 canvases that feel remembered rather than observed.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-inchbold",
    venue_id: "v-hazelhurst-arts-centre",
    title: "Mango Flesh Identikit",
    artists: "Edward Inchbold",
    start_date: "2026-07-10",
    end_date: "2026-07-28",
    opening_datetime: null,
    description:
      "Inchbold's new paintings hold two readings at once \u2014 identity and memory worked over until the image refuses to settle.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-tobin",
    venue_id: "v-penrith-regional-gallery",
    title: "Ngalawan: We Live",
    artists: "Leanne Tobin",
    start_date: "2026-07-04",
    end_date: "2026-11-01",
    opening_datetime: null,
    description:
      "Dharug artist Leanne Tobin on Country, presence and persistence \u2014 the gallery's major solo through spring.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-youth-prize",
    venue_id: "v-penrith-regional-gallery",
    title: "Penrith Youth Art Prize 2026",
    artists: "Young artists of the Penrith region",
    start_date: "2026-06-27",
    end_date: "2026-09-09",
    opening_datetime: null,
    description:
      "The region's youngest artists on the big walls \u2014 an annual prize show with more nerve than polish, in the best way.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-we-are-here",
    venue_id: "v-fairfield-city-museum-gallery",
    title: "We Are Here",
    artists: "Fairfield communities",
    start_date: "2026-04-11",
    end_date: "2026-09-19",
    opening_datetime: null,
    description:
      "Fairfield's communities tell their own arrival stories \u2014 a museum show built from the suburb outward.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-entangled",
    venue_id: "v-hawkesbury-regional-gallery",
    title: "Entangled Grounds",
    artists: "Yandell Walton, Mar Seriny\u00e0 Gou",
    start_date: "2026-06-06",
    end_date: "2026-08-23",
    opening_datetime: null,
    description:
      "Walton and Seriny\u00e0 Gou turn residencies on the edge of Wollemi National Park into work about roots, networks and what connects underneath.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-woven-flowers",
    venue_id: "v-hurstville-museum-gallery",
    title: "Woven from a hundred flowers",
    artists: "Nepalese community artists of the Georges River",
    start_date: "2026-05-01",
    end_date: "2026-08-30",
    opening_datetime: null,
    description:
      "Stories and textiles of the Nepalese community of the Georges River \u2014 culture carried in cloth.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-pari-domain",
    venue_id: "v-pari",
    title: "Domain",
    artists: "Chloe Abdelnour, Katerina Asistin, Lingam Brown & others",
    start_date: "2026-06-21",
    end_date: "2026-08-16",
    opening_datetime: null,
    description:
      "Western Sydney voices on their own terms \u2014 Pari's group show holds the neighbourhood close.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-aspden",
    venue_id: "v-utopia-art-sydney",
    title: "David Aspden",
    artists: "David Aspden",
    start_date: "2026-07-25",
    end_date: "2026-08-15",
    opening_datetime: null,
    description:
      "Unseen major Aspdens from the 1970s \u2014 colour as weather \u2014 opening the gallery's new Waterloo rooms.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-gaha",
    venue_id: "v-martin-browne-contemporary",
    title: "Introspection",
    artists: "Adrienne Gaha",
    start_date: "2026-07-04",
    end_date: "2026-07-25",
    opening_datetime: null,
    description:
      "Gaha's veiled, luminous canvases \u2014 painting that looks inward and lets the light do the arguing.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-espinosa",
    venue_id: "v-martin-browne-contemporary",
    title: "La Madrug\u00e1",
    artists: "Rose Espinosa",
    start_date: "2026-07-04",
    end_date: "2026-07-25",
    opening_datetime: null,
    description:
      "Espinosa's small hours \u2014 works named for the hush before dawn, hung alongside Gaha's Introspection.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-taweel",
    venue_id: "v-mosman-art-gallery",
    title: "Shireen Taweel: the trig point",
    artists: "Shireen Taweel",
    start_date: "2026-05-16",
    end_date: "2026-08-09",
    opening_datetime: null,
    description:
      "Taweel maps sacred architecture onto the observatory \u2014 a silk house of seven circles and a sonic score of navigation, migration and faith.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-casey-chen",
    venue_id: "v-mosman-art-gallery",
    title: "Merciful Navigation",
    artists: "Casey Chen",
    start_date: "2026-05-16",
    end_date: "2026-08-09",
    opening_datetime: null,
    description:
      "Chen redraws a mythical Song-dynasty China through ceramic tradition and pop culture \u2014 an allegorical map of a country in turmoil.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-evolution",
    venue_id: "v-gallery-lane-cove",
    title: "Evolution: Founders of the Indigenous Art Movement",
    artists: "Albert Namatjira, Emily Kngwarreye, Ronnie Tjampitjinpa & others",
    start_date: "2026-07-01",
    end_date: "2026-07-25",
    opening_datetime: null,
    description:
      "Namatjira, Kngwarreye, Tjampitjinpa \u2014 the founders of the desert painting movement, curated by Brenda Colahan at Lane Cove.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-threadlines",
    venue_id: "v-art-space-on-the-concourse",
    title: "THREADLINES",
    artists: "Five First Nations artists, curated by Nicole Monks",
    start_date: "2026-07-02",
    end_date: "2026-08-02",
    opening_datetime: null,
    description:
      "Weaving as method, collaboration as subject \u2014 five artists in residence, with work spilling into the library next door.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-operation-art",
    venue_id: "v-art-space-on-the-concourse",
    title: "Operation Art 2026",
    artists: "NSW school students for Westmead Children's Hospital",
    start_date: "2026-08-08",
    end_date: "2026-10-04",
    opening_datetime: null,
    description:
      "Schoolchildren painting for the children's hospital \u2014 hundreds of small works of unguarded sincerity, picked for the wards at Westmead.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
  {
    id: "e-after-hours",
    venue_id: "v-dominik-mersch-gallery",
    title: "DMG Curator Award 2026: After Hours",
    artists: "Group show curated by Liam Garstang",
    start_date: "2026-07-10",
    end_date: "2026-08-01",
    opening_datetime: null,
    description:
      "Curator Award winner Liam Garstang keeps the lights on late \u2014 a group show about what work does to time.",
    image_url: null,
    status: 'approved',
    rejection_reason: null,
    is_featured: false,
    city: 'Sydney',
  },
];

// Art-medium tags for the seeded agenda (migration 0017). Kept as a map so
// the exhibition entries above stay readable; shows not listed here stay
// untagged and simply sit outside the medium filters.
const SEED_MEDIUMS: Record<string, string[]> = {
  'e-archibald': ['contemporary', 'figurative'],
  'e-murakami': ['contemporary', 'pop_art'],
  'e-primavera': ['contemporary', 'conceptual'],
  'e-armanious': ['contemporary', 'conceptual'],
  'e-kahukiwa': ['figurative', 'first_nations'],
  'e-nell': ['contemporary', 'conceptual'],
  'e-constructed-world': ['contemporary', 'conceptual'],
  'e-bennett': ['contemporary'],
  'e-gabori-ledgerwood': ['abstract', 'first_nations'],
  'e-infinite-gesture': ['abstract'],
  'e-crothers': ['contemporary', 'abstract'],
  'e-pulse': ['contemporary', 'digital_art'],
  'e-abbotsleigh': ['contemporary'],
  'e-black-myth': ['contemporary', 'surrealism'],
  'e-nsw-fellowship': ['contemporary'],
  'e-undying': ['contemporary'],
  'e-unkept': ['contemporary'],
  'e-salon-des-refuses': ['figurative'],
  'e-mitch-cairns': ['contemporary', 'figurative'],
  'e-jasper-knight': ['contemporary', 'figurative'],
  'e-tamara-dean': ['contemporary', 'figurative'],
  'e-min-wong': ['contemporary', 'conceptual'],
  'e-chronos': ['digital_art'],
  'e-friends-annual': ['contemporary'],
  'e-dorabialski': ['contemporary', 'abstract'],
  'e-bartley': ['contemporary', 'abstract'],
  'e-nhan': ['contemporary', 'figurative'],
};
for (const e of SEED_EXHIBITIONS) e.mediums = SEED_MEDIUMS[e.id] ?? [];
