-- ART EYE — zet de 61 geverifieerde tentoonstellingen in de LIVE database.
-- Plak dit EEN keer in de SQL Editor en druk Run. Veilig om te herhalen:
-- shows die er al staan (zelfde venue + titel) worden overgeslagen, en de
-- wachtrij van de motor blijft onaangeroerd.
-- Gegenereerd uit src/lib/seed.ts (de geverifieerde app-data).

with seed (slug, title, artists, start_date, end_date, description, image_url, is_featured) as (
  values
  ('art-gallery-of-new-south-wales', 'Archibald, Wynne & Sulman Prizes 2026', 'Finalists 2026', '2026-05-09', '2026-08-16', 'Australia’s most argued-over walls. The Archibald’s portraits, the Wynne’s landscapes and the Sulman’s subject pictures hang side by side — a yearly census of who we are and how we want to be seen.', null, true),
  ('art-gallery-of-new-south-wales', 'Takashi Murakami', 'Takashi Murakami', '2026-12-05', '2027-07-18', 'The superflat universe at full scale — smiling flowers, silver screens and centuries of Japanese painting compressed into one relentless surface. Murakami’s first major Sydney survey.', 'https://upload.wikimedia.org/wikipedia/commons/8/80/Takashi_Murakami_at_Versailles_Sept._2010_%281%29.jpg', true),
  ('mca-australia', 'Primavera 2026: Young Australian Artists', 'Young Australian Artists', '2026-06-27', '2026-09-28', 'The MCA’s annual exhibition of Australian artists aged 35 and under — the clearest early signal of where Australian art is going next.', null, true),
  ('mca-australia', 'Hany Armanious: The Planets', 'Hany Armanious', '2026-07-10', '2026-10-26', 'Casts of the overlooked — foam, wax, candle stubs, offcuts — remade with such fidelity that the ordinary turns uncanny. A survey of one of Australia’s most quietly influential sculptors.', null, false),
  ('mca-australia', 'Robyn Kahukiwa: My Ancestors Are Always With Me', 'Robyn Kahukiwa', '2026-10-14', '2027-02-07', 'Paintings that carry whakapapa like a current — the late Māori artist’s figures of women and ancestors, political and tender at once, gathered for Sydney audiences.', null, false),
  ('mca-australia', 'Nell: Loti Smorgon Sculpture Terrace Commission', 'Nell', '2026-08-26', '2027-08-23', 'A new commission by Nell — where rock’n’roll, Buddhism and the eucalypt meet. On the MCA’s public-facing spaces through spring.', null, false),
  ('roslyn-oxley9-gallery', 'A Constructed World', 'A Constructed World', '2026-06-26', '2026-07-18', 'The collaborative practice of Geoff Lowe and Jacqueline Riva — painting, performance and speech acts that keep meaning deliberately unstable.', null, false),
  ('cassandra-bird', 'Places of Delight', 'Robby Bennett', '2026-06-19', '2026-08-01', 'New paintings by Robby Bennett — gardens, rooms and remembered places rendered as sites of pleasure and slight unease.', null, false),
  ('1301sw', 'Sally Gabori & Judy Ledgerwood', 'Sally Gabori, Judy Ledgerwood', '2026-06-13', '2026-07-11', 'Two painters of colour at scale, an ocean apart — Gabori’s Kaiadilt country in saturated fields beside Ledgerwood’s rhythmic Chicago abstraction.', null, false),
  ('ames-yavuz', 'Infinite Gesture', 'Group Exhibition', '2026-07-04', '2026-08-08', 'A group exhibition on the mark as a unit of thought — gesture repeated, extended and abstracted across painting and works on paper.', null, false),
  ('olsen-annexe', 'Interconnected', 'Aaron Crothers', '2026-07-22', '2026-08-15', 'Aaron Crothers maps the systems beneath landscape — geology, weather, root and network — in paintings that read like aerial diagrams of connection.', null, false),
  ('grace-cossington-smith-gallery', 'Pulse', 'Group Exhibition', '2026-06-12', '2026-07-11', 'Works that take rhythm as subject and method — repetition, beat and breath across media at the Grace Cossington Smith Gallery.', null, false),
  ('grace-cossington-smith-gallery', 'Abbotsleigh Biennial: Finalists', 'Biennial Finalists', '2026-07-18', '2026-08-15', 'Finalists of the Abbotsleigh Biennial — a cross-section of current practice selected for the gallery’s biennial exhibition and prize.', null, false),
  ('white-rabbit-gallery', 'Black Myth', 'White Rabbit Collection artists', '2026-06-25', '2026-11-08', 'Drawn from the Judith Neilson collection — new Chinese art that reaches for the mythic: gods, ghosts and machines tangled in one dark, spectacular sweep across all four floors.', null, true),
  ('artspace', '2026 NSW Visual Arts Fellowship (Emerging)', 'Virginia Keft, Charles Levi, Tia Madden, Amelia Skelton, Sue Jo Wright, Natasha & Caitlin Dubler', '2026-07-03', '2026-09-06', 'Six emerging practices in one charged room — the state’s sharpest early-career artists make their case for the Fellowship at The Gunnery.', null, false),
  ('chau-chak-wing-museum', 'Undying: Abdul-Rahman Abdullah', 'Abdul-Rahman Abdullah', '2026-02-07', '2026-07-26', 'Hand-carved animals meet the museum’s natural history collection — Abdullah’s tender, uncanny menagerie on our entangled lives with the creatures we keep, fear and mourn.', null, false),
  ('chau-chak-wing-museum', 'Unkept: Kirtika Kain', 'Kirtika Kain', '2026-02-07', '2026-07-26', 'In a makeshift storehouse in the Penelope Gallery, Kain works gold, tar and pigment into a reckoning with caste, labour and the histories archives fail to keep.', null, false),
  ('sh-ervin-gallery', 'Salon des Refusés 2026', 'The alternative Archibald & Wynne selection', '2026-05-09', '2026-07-26', 'The ones that got away — the annual alternative selection from the Archibald and Wynne entries, hung on Observatory Hill and argued over just as fiercely.', null, false),
  ('nas-gallery', 'Mitch Cairns: Artist’s Mouth', 'Mitch Cairns', '2026-05-01', '2026-07-11', 'Twenty years of Cairns’ cool, exact painting — 48 works, the 2017 Archibald winner among them — surveyed in the old Darlinghurst Gaol where he trained.', null, false),
  ('mosman-art-gallery', 'Jasper Knight: Collage, prints and works on paper', 'Jasper Knight', '2026-06-01', '2026-08-09', 'Harbour light at speed — Knight’s cut, layered and printed Sydney, from ferries to pylons, in a survey of his works on paper at Mosman.', null, false),
  ('manly-art-gallery-museum', 'Tamara Dean: Leave Only Footprints', 'Tamara Dean', '2026-06-12', '2026-08-02', 'Bodies folded into bushland, ocean and storm — the first survey of Dean’s staged photomedia, where the human figure is one animal among many.', null, false),
  ('manly-art-gallery-museum', 'Min Wong: You shall definitely pass', 'Min Wong', '2026-06-12', '2026-08-02', 'Fresh from residencies in Berlin and Athens, Wong builds an immersive installation on power, belonging and the promises of self-improvement.', null, false),
  ('manly-art-gallery-museum', 'Chronos: Australian ceramics from 1933', 'Australian ceramicists, 1933 to now', '2026-03-21', '2027-03-14', 'Nine decades of Australian clay — how ceramic practice holds and hands on cultural change, traced through the gallery’s collection.', null, false),
  ('campbelltown-arts-centre', 'Friends Annual & Focus: Zara Collins', 'Friends of Campbelltown Arts Centre, Zara Collins', '2026-06-27', '2026-09-13', 'The region’s artists on their own walls — the Friends’ eclectic annual across styles and mediums, with Zara Collins as this year’s Focus artist.', null, false),
  ('firstdraft', 'You wouldn’t remember him', 'Nina Dorabialski', '2026-07-18', '2026-08-22', 'The family album, present only by inference — Dorabialski circles the pictures never shown, unsettling the stories nuclear families tell about themselves.', null, false),
  ('king-street-gallery', 'The Quick and the Slow', 'John Bartley', '2026-07-07', '2026-08-01', 'Bartley’s new paintings hold two speeds at once — quick marks over slow ground, landscape as something felt in tempo rather than seen in place.', null, false),
  ('king-street-gallery', 'Proverbial', 'Nathan Nhan', '2026-07-07', '2026-08-01', 'Nhan takes the worn wisdom of proverbs and paints it strange again — inherited sayings tested against a first-generation present.', null, false),
  ('wollongong-art-gallery', 'Once Upon a Doll', 'Raquel Caballero', '2026-07-03', '2026-11-01', 'Sixteen hand-built dolls by Raquel Caballero — craft turned uncanny, childhood forms carrying very adult freight.', null, false),
  ('wollongong-art-gallery', 'Popular Versus Culture', 'Georgia Banks', '2026-06-06', '2026-09-06', 'Made in the wake of a residency at The Andy Warhol Museum, Banks pushes Warhol''s obsession with fame and fandom into the feed-scroll present.', null, false),
  ('ngununggula', 'New Religion', 'Hayley Millar Baker, Nell, Julia Robinson, Brent Harris & others', '2026-06-27', '2026-10-18', 'Faith and its afterimages — contemporary work alongside loans from the AGNSW and NGA, from Dürer to now, on symbols that outlive belief.', null, false),
  ('bundanon', 'Man on Fire: Visions of Nebuchadnezzar', 'Arthur Boyd, Shaun Gladwell', '2026-07-04', '2026-10-11', 'Boyd''s Nebuchadnezzar paintings — a king burning through his own hubris — meet a major new Shaun Gladwell commission on the same unravelling.', null, true),
  ('blue-mountains-cultural-centre', 'The Art of Adaptation', 'Kandos School of Cultural Adaptation', '2026-06-20', '2026-08-02', 'The Kandos School of Cultural Adaptation brings its field-tested art-and-land experiments to Katoomba — practical, hopeful, unromantic.', null, false),
  ('newcastle-art-gallery', 'Brian Robinson: Multiverse', 'Brian Robinson', '2026-05-23', '2026-08-30', 'The Torres Strait Islander artist''s first major NSW solo — monumental linocuts, larger-than-life sculpture and an immersive animation in the reopened gallery.', null, false),
  ('newcastle-art-gallery', 'Tiyan Baker', 'Tiyan Baker', '2026-07-25', '2026-09-06', 'Baker''s first institutional solo, on home ground — part of the reopened Newcastle Art Gallery''s statement 2026 program.', null, false),
  ('the-lock-up', 'Into the Dark', 'Wendy Sharpe', '2026-07-18', '2026-09-13', 'Archibald winner Wendy Sharpe paints the night side — staged in the cells of a former police lock-up, which suits the work.', null, false),
  ('gosford-regional-gallery', '20 x 20 Art Exhibition 2026', 'Central Coast artists, anonymous until sold', '2026-07-22', '2026-08-03', 'A wall of anonymous 20-centimetre squares at $100 each — the annual leveller where a name means nothing until the red dot goes up.', null, false),
  ('gosford-regional-gallery', 'Confluence', 'David Collins, Ana Pollak', '2026-07-25', '2026-09-13', 'Partners for forty years, Collins and Pollak hang side by side — two practices that meet the way rivers do, keeping their own currents.', null, false),
  ('carriageworks', 'Sydney Contemporary 2026', '100+ galleries, 500+ artists', '2026-09-03', '2026-09-06', 'The southern hemisphere''s biggest art fair takes over the Eveleigh rail sheds — a hundred galleries, five hundred artists, four dense days.', null, false),
  ('4a-centre', 'Archetypes: 30 Years of 4A', 'Asian-Australian artists across three decades', '2026-07-11', '2026-09-20', 'Three decades of Asian-Australian art and advocacy — new commissions hung against the archive that made them possible.', null, false),
  ('nas-gallery', 'Margaret Olley: Australian Intimiste', 'Margaret Olley', '2026-07-31', '2026-10-25', 'Interiors, ranunculus, the unmade table — the National Art School honours its most beloved alum with a full survey of the great intimiste.', null, true),
  ('hazelhurst-arts-centre', 'Milli Jannides', 'Milli Jannides', '2026-07-04', '2026-08-30', 'Dreamlike, loose-limbed painting from the Sydney-born, Aotearoa-based Jannides — canvases that feel remembered rather than observed.', null, false),
  ('hazelhurst-arts-centre', 'Mango Flesh Identikit', 'Edward Inchbold', '2026-07-10', '2026-07-28', 'Inchbold''s new paintings hold two readings at once — identity and memory worked over until the image refuses to settle.', null, false),
  ('penrith-regional-gallery', 'Ngalawan: We Live', 'Leanne Tobin', '2026-07-04', '2026-11-01', 'Dharug artist Leanne Tobin on Country, presence and persistence — the gallery''s major solo through spring.', null, false),
  ('penrith-regional-gallery', 'Penrith Youth Art Prize 2026', 'Young artists of the Penrith region', '2026-06-27', '2026-09-09', 'The region''s youngest artists on the big walls — an annual prize show with more nerve than polish, in the best way.', null, false),
  ('fairfield-city-museum-gallery', 'We Are Here', 'Fairfield communities', '2026-04-11', '2026-09-19', 'Fairfield''s communities tell their own arrival stories — a museum show built from the suburb outward.', null, false),
  ('hawkesbury-regional-gallery', 'Entangled Grounds', 'Yandell Walton, Mar Serinyà Gou', '2026-06-06', '2026-08-23', 'Walton and Serinyà Gou turn residencies on the edge of Wollemi National Park into work about roots, networks and what connects underneath.', null, false),
  ('hurstville-museum-gallery', 'Woven from a hundred flowers', 'Nepalese community artists of the Georges River', '2026-05-01', '2026-08-30', 'Stories and textiles of the Nepalese community of the Georges River — culture carried in cloth.', null, false),
  ('pari', 'Domain', 'Chloe Abdelnour, Katerina Asistin, Lingam Brown & others', '2026-06-21', '2026-08-16', 'Western Sydney voices on their own terms — Pari''s group show holds the neighbourhood close.', null, false),
  ('utopia-art-sydney', 'David Aspden', 'David Aspden', '2026-07-25', '2026-08-15', 'Unseen major Aspdens from the 1970s — colour as weather — opening the gallery''s new Waterloo rooms.', null, false),
  ('martin-browne-contemporary', 'Introspection', 'Adrienne Gaha', '2026-07-04', '2026-07-25', 'Gaha''s veiled, luminous canvases — painting that looks inward and lets the light do the arguing.', null, false),
  ('martin-browne-contemporary', 'La Madrugá', 'Rose Espinosa', '2026-07-04', '2026-07-25', 'Espinosa''s small hours — works named for the hush before dawn, hung alongside Gaha''s Introspection.', null, false),
  ('mosman-art-gallery', 'Shireen Taweel: the trig point', 'Shireen Taweel', '2026-05-16', '2026-08-09', 'Taweel maps sacred architecture onto the observatory — a silk house of seven circles and a sonic score of navigation, migration and faith.', null, false),
  ('mosman-art-gallery', 'Merciful Navigation', 'Casey Chen', '2026-05-16', '2026-08-09', 'Chen redraws a mythical Song-dynasty China through ceramic tradition and pop culture — an allegorical map of a country in turmoil.', null, false),
  ('gallery-lane-cove', 'Evolution: Founders of the Indigenous Art Movement', 'Albert Namatjira, Emily Kngwarreye, Ronnie Tjampitjinpa & others', '2026-07-01', '2026-07-25', 'Namatjira, Kngwarreye, Tjampitjinpa — the founders of the desert painting movement, curated by Brenda Colahan at Lane Cove.', null, false),
  ('art-space-on-the-concourse', 'THREADLINES', 'Five First Nations artists, curated by Nicole Monks', '2026-07-02', '2026-08-02', 'Weaving as method, collaboration as subject — five artists in residence, with work spilling into the library next door.', null, false),
  ('art-space-on-the-concourse', 'Operation Art 2026', 'NSW school students for Westmead Children''s Hospital', '2026-08-08', '2026-10-04', 'Schoolchildren painting for the children''s hospital — hundreds of small works of unguarded sincerity, picked for the wards at Westmead.', null, false),
  ('dominik-mersch-gallery', 'DMG Curator Award 2026: After Hours', 'Group show curated by Liam Garstang', '2026-07-10', '2026-08-01', 'Curator Award winner Liam Garstang keeps the lights on late — a group show about what work does to time.', null, false),
  ('art-gallery-of-new-south-wales', 'Super Nature', 'Group Exhibition', '2026-03-14', '2027-02-01', 'Four thematic spaces on the ties between people and the environment — gardens as memorials, the wild nature that lives alongside us, and the cultivation of nature for survival. Free entry.', null, false),
  ('art-gallery-of-new-south-wales', 'Avatar: Forms of Vishnu', 'South and Southeast Asian art', '2026-06-20', '2026-10-05', 'Centuries of art and storytelling from South and Southeast Asia celebrating Vishnu, the Hindu deity believed to preserve order in the universe.', null, false),
  ('art-gallery-of-new-south-wales', 'Nolan: Origins', 'Sidney Nolan', '2026-10-03', '2027-02-07', 'A major survey of Sidney Nolan''s formative years in Australia — the making of one of the country''s defining modern painters.', null, false),
  ('mca-australia', 'Tony Albert: Not a Souvenir', 'Tony Albert', '2026-05-21', '2026-10-19', 'A major survey across sculpture, photography, installation and painting — Albert turns The Rocks'' souvenir culture back on itself, confronting the commodification of Aboriginal people while celebrating survival and pride. Guest curated by Bruce Johnson McLean.', null, false)
)
insert into exhibitions (venue_id, title, artists, start_date, end_date, description, image_url, status, is_featured, city)
select v.id, s.title, s.artists, s.start_date::date, s.end_date::date, s.description, s.image_url, 'approved', s.is_featured, 'Sydney'
from seed s
join venues v on v.slug = s.slug
where not exists (
  select 1 from exhibitions e
  where e.venue_id = v.id and lower(e.title) = lower(s.title)
);

-- Controle: hoeveel staan er nu live?
select count(*) as exhibitions_live from exhibitions;
