// Generate a small tileable grain PNG. Real texture, not a gradient: the
// point of the whole exercise.
import zlib from 'zlib';
import { writeFileSync } from 'fs';

const SIZE = 96;

function crc32(buf) {
  let c, crc = 0xFFFFFFFF;
  for (let n = 0; n < buf.length; n++) {
    c = (crc ^ buf[n]) & 0xFF;
    for (let k = 0; k < 8; k++) c = c & 1 ? 0xEDB88320 ^ (c >>> 1) : c >>> 1;
    crc = c ^ (crc >>> 8);
  }
  return (crc ^ 0xFFFFFFFF) >>> 0;
}

function chunk(type, data) {
  const len = Buffer.alloc(4);
  len.writeUInt32BE(data.length);
  const td = Buffer.concat([Buffer.from(type, 'ascii'), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(td));
  return Buffer.concat([len, td, crc]);
}

// RGBA scanlines, filter byte 0 per row. Each pixel is either white or black
// at a low random alpha, so the same tile reads as grain on any ground.
const raw = Buffer.alloc(SIZE * (SIZE * 4 + 1));
let p = 0;
for (let y = 0; y < SIZE; y++) {
  raw[p++] = 0;
  for (let x = 0; x < SIZE; x++) {
    const light = Math.random() > 0.5;
    const v = light ? 255 : 0;
    raw[p++] = v; raw[p++] = v; raw[p++] = v;
    raw[p++] = Math.floor(Math.random() * 46); // 0..45 alpha
  }
}

const ihdr = Buffer.alloc(13);
ihdr.writeUInt32BE(SIZE, 0);
ihdr.writeUInt32BE(SIZE, 4);
ihdr[8] = 8;   // bit depth
ihdr[9] = 6;   // colour type: RGBA
const png = Buffer.concat([
  Buffer.from([0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]),
  chunk('IHDR', ihdr),
  chunk('IDAT', zlib.deflateSync(raw, { level: 9 })),
  chunk('IEND', Buffer.alloc(0)),
]);

const b64 = png.toString('base64');
writeFileSync(process.argv[2], `// Generated by scripts/make-grain.mjs — a tileable 96px grain, so texture
// comes from real pixels rather than another gradient.
export const GRAIN_URI = 'data:image/png;base64,${b64}';
export const GRAIN_SIZE = ${SIZE};
`);
console.log('grain bytes:', png.length, '| base64 chars:', b64.length);
